local M = {}
local asset_urls = April.require("game.asset_urls")
local DIALOGUE_ROOT = asset_urls.CDN_BASE .. "/anime/april/"

local function bind_character(ch)
    function ch.sprite_file(expression)
        return (ch.expressions[expression] or ch.expressions.neutral) .. ".png"
    end
    function ch.url(expression)
        return ch.urls(expression)[1]
    end
    function ch.urls(expression)
        return asset_urls.anime_sprite_urls(ch.folder or ch.id, ch.sprite_file(expression))
    end
    return ch
end

local H = bind_character({
    id = "april",
    folder = "april",
    name = "April",
    aspect = 346 / 400,
    mouth_x = 0.56,
    mouth_y = 0.30,
    expressions = {
        neutral = "normal", smile = "smile", happy = "happy", laugh = "hah",
        smug = "angrysmile", pout = "pout", worried = "worried", fear = "fear",
        sad = "sad", disgusted = "disgusted", evil = "evil", surprised = "oh",
    },
    dialogue = {},
})

-- VectorChan mascot: 4 emotion sprites mapped onto April's dialogue expression keys.
local V = bind_character({
    id = "vector",
    folder = "vector",
    name = "VectorChan",
    aspect = 346 / 400,
    -- Measured from angry.png mouth/teeth band (~176x, ~184y on 346x400).
    mouth_x = 0.51,
    mouth_y = 0.485,
    expressions = {
        neutral = "neutral", smile = "happy", happy = "happy", laugh = "happy",
        smug = "angry", pout = "sad", worried = "sad", fear = "sad",
        sad = "sad", disgusted = "angry", evil = "angry", surprised = "angry",
    },
    dialogue = {},
})

-- Offline + bundled dialogue. Remote refresh optional.
local DIALOGUE_EN = {
    "greeting|roasty|smug|Oh, you enabled me? Fine. Try not to embarrass us.",
    "greeting|roasty|pout|I was having a nice day until you clicked that toggle.",
    "greeting|roasty|evil|Your personal commentator has arrived. This should be funny.",
    "greeting|roasty|laugh|I'm ready. Give me something worth making fun of.",
    "greeting|roasty|neutral|April online. Expectations remain dangerously low.",
    "greeting|roasty|disgusted|You called? I hope your gameplay improved while I was gone.",
    "greeting|supportive|smile|April online. I'll keep an eye on you.",
    "greeting|supportive|happy|Ready when you are. Let's survive this one.",
    "greeting|supportive|neutral|I'm here. Stay sharp and we'll be fine.",
    "greeting|supportive|smile|All set! Try to come back in one piece.",
    "greeting|supportive|happy|Your favorite announcer is ready to go.",
    "greeting|supportive|neutral|Systems ready. I'll call out anything important.",
    "death|roasty|laugh|You suck, lol. Want to try that again?",
    "death|roasty|disgusted|That was your plan? Seriously?",
    "death|roasty|smug|Another tactical donation to the enemy.",
    "death|roasty|pout|I looked away for one second and you died.",
    "death|roasty|evil|Excellent performance. Zero notes. Zero pulse, too.",
    "death|roasty|laugh|Speedrunning the respawn screen again?",
    "death|roasty|disgusted|Maybe the bullets will miss if you stand even stiller next time.",
    "death|roasty|smug|Good news: the ground successfully caught you.",
    "death|roasty|pout|Please stop making death look like a hobby.",
    "death|roasty|laugh|They barely had to try. That's almost impressive.",
    "death|roasty|evil|A flawless demonstration of what not to do.",
    "death|roasty|disgusted|Your survival instincts filed for resignation.",
    "death|roasty|smug|I have seen training dummies with better positioning.",
    "death|roasty|pout|That life had a shorter runtime than this speech bubble.",
    "death|supportive|sad|That one hurt. Reset and take it slower.",
    "death|supportive|worried|You're down, but it isn't over. Learn the angle.",
    "death|supportive|smile|Bad round. Fresh start.",
    "death|supportive|sad|Unlucky. We'll get it back next life.",
    "death|supportive|worried|Breathe. Think about what exposed you.",
    "death|supportive|neutral|Death confirmed. Time to adjust the plan.",
    "death|supportive|smile|Shake it off. The next life is yours.",
    "death|supportive|sad|That was rough, but now you know where they were.",
    "death|supportive|worried|Review the mistake, then leave it behind.",
    "death|supportive|neutral|One bad fight does not decide the session.",
    "respawn|roasty|smug|Back already? Try keeping this body for a minute.",
    "respawn|roasty|pout|New life, same questionable decision-making.",
    "respawn|roasty|evil|Round two. Surely nothing could go wrong.",
    "respawn|roasty|laugh|The respawn button deserves overtime pay.",
    "respawn|roasty|neutral|Welcome back. I saved your dignity. There wasn't much.",
    "respawn|roasty|smug|Fresh body delivered. Handle with slightly more care.",
    "respawn|roasty|pout|Okay, no dying immediately. That's the whole assignment.",
    "respawn|roasty|laugh|Look who escaped the loading screen.",
    "respawn|supportive|happy|You're back. New life, clean slate.",
    "respawn|supportive|smile|Respawned and ready. Take your time.",
    "respawn|supportive|neutral|Fresh start. Check your surroundings first.",
    "respawn|supportive|happy|There you are. Let's make this life count.",
    "respawn|supportive|smile|Back in action. Recover your rhythm.",
    "respawn|supportive|neutral|Respawn complete. Rebuild before taking another fight.",
    "respawn|supportive|happy|New life ready. Start with a safe route.",
    "respawn|supportive|smile|Welcome back. Focus on one good decision at a time.",
    "downed|roasty|laugh|Floor inspection going well?",
    "downed|roasty|smug|You found the downed state. Very thorough testing.",
    "downed|roasty|pout|Crawling is not a combat strategy.",
    "downed|roasty|disgusted|This is why I told you to use cover.",
    "downed|roasty|evil|Technically alive. Emotionally? Debatable.",
    "downed|roasty|laugh|Wave to your teammates from down there.",
    "downed|roasty|worried|Someone revive the professional floor ornament.",
    "downed|roasty|smug|Outstanding posture. Ten out of ten.",
    "downed|supportive|worried|You're downed. Get behind cover and call for help.",
    "downed|supportive|fear|Stay low. A teammate may still reach you.",
    "downed|supportive|sad|Don't give up yet. Crawl somewhere safe.",
    "downed|supportive|worried|Downed, not dead. Break line of sight.",
    "downed|supportive|neutral|Save your movement and wait for the revive.",
    "downed|supportive|fear|Careful, one more hit could finish this.",
    "downed|supportive|sad|Keep moving toward cover if it is safe.",
    "downed|supportive|worried|Call your position and let your team work.",
    "revived|roasty|smug|Someone actually picked you up. Be grateful.",
    "revived|roasty|pout|You're standing again. Please make it worth their time.",
    "revived|roasty|laugh|Revived! The floor will miss you.",
    "revived|roasty|evil|Second chance acquired. Bad ideas re-enabled.",
    "revived|roasty|neutral|Back on your feet. Try using them this time.",
    "revived|roasty|smug|Your teammate has unreasonable faith in you.",
    "revived|supportive|happy|You're up! Heal before re-engaging.",
    "revived|supportive|smile|Nice recovery. Find cover and reset.",
    "revived|supportive|worried|Revived. Don't peek until you're healthy.",
    "revived|supportive|happy|Good save. Stay with your team now.",
    "revived|supportive|neutral|Back on your feet. Stabilize first.",
    "revived|supportive|smile|Second chance secured. Make it count.",
    "low_health|roasty|worried|Your health bar is practically decorative now.",
    "low_health|roasty|pout|One sneeze and you're back at respawn.",
    "low_health|roasty|smug|Bold strategy, fighting with three pixels of health.",
    "low_health|roasty|fear|Maybe stop peeking? Just a thought.",
    "low_health|roasty|disgusted|Heal. The red screen is not an aesthetic choice.",
    "low_health|roasty|worried|You are held together by confidence and bad math.",
    "low_health|roasty|pout|Please locate medicine before locating another bullet.",
    "low_health|roasty|smug|Living on one hit point is not a personality.",
    "low_health|supportive|worried|Low health. Disengage and heal now.",
    "low_health|supportive|fear|You're critical. Find hard cover.",
    "low_health|supportive|sad|Don't take another fight until you recover.",
    "low_health|supportive|worried|Health is low. Slow down and reset.",
    "low_health|supportive|neutral|Critical health. Prioritize survival.",
    "low_health|supportive|fear|Break line of sight and heal.",
    "low_health|supportive|worried|Do not trade damage right now.",
    "low_health|supportive|neutral|Find safety, heal, then reassess.",
    "recovered|roasty|smug|Health restored. Common sense still pending.",
    "recovered|roasty|smile|Patched up and ready to make new mistakes.",
    "recovered|roasty|laugh|Look at that, you discovered healing.",
    "recovered|roasty|pout|Better. Don't immediately waste it.",
    "recovered|roasty|evil|Fuller health bar, renewed capacity for chaos.",
    "recovered|roasty|neutral|You survived the medicine tutorial.",
    "recovered|supportive|happy|Health recovered. You're ready again.",
    "recovered|supportive|smile|Good reset. Choose the next fight carefully.",
    "recovered|supportive|neutral|Stable again. Recheck ammo and surroundings.",
    "recovered|supportive|happy|Nice recovery. Keep that momentum.",
    "recovered|supportive|smile|Much better. Stay disciplined.",
    "recovered|supportive|neutral|Recovery complete. Return when the timing is right.",
    "safe_enter|roasty|smug|Safe zone reached. Even you should survive in here.",
    "safe_enter|roasty|laugh|Congratulations, the game is protecting you now.",
    "safe_enter|roasty|pout|You're safe. Try not to trip over anything.",
    "safe_enter|roasty|neutral|Safe zone. Your danger privileges are temporarily revoked.",
    "safe_enter|roasty|smile|A peaceful moment for your overworked respawn key.",
    "safe_enter|roasty|evil|Enjoy safety while it lasts.",
    "safe_enter|supportive|happy|Safe zone reached. Take a moment to reset.",
    "safe_enter|supportive|smile|You're safe. Sort your inventory and plan ahead.",
    "safe_enter|supportive|neutral|Safe zone entered. Good time to regroup.",
    "safe_enter|supportive|happy|Made it safely. Restock before leaving.",
    "safe_enter|supportive|smile|You're protected here. Use the breathing room.",
    "safe_enter|supportive|neutral|Take stock of what you need before heading out.",
    "safe_leave|roasty|evil|Leaving safety? This should be entertaining.",
    "safe_leave|roasty|smug|Protection off. Let's see how long this lasts.",
    "safe_leave|roasty|pout|Back into danger with absolutely no supervision.",
    "safe_leave|roasty|laugh|Safe zone left. Respawn screen standing by.",
    "safe_leave|roasty|neutral|You're vulnerable again. Pretend to be careful.",
    "safe_leave|roasty|evil|And there goes your last good excuse.",
    "safe_leave|supportive|worried|Leaving the safe zone. Check your route.",
    "safe_leave|supportive|neutral|Protection ended. Stay aware of nearby players.",
    "safe_leave|supportive|smile|Back outside. Move with purpose.",
    "safe_leave|supportive|worried|You're exposed again. Keep cover nearby.",
    "safe_leave|supportive|neutral|Safe zone left. Watch your surroundings.",
    "safe_leave|supportive|smile|Route checked? Then let's move.",
    "combat_enter|roasty|evil|Combat started. Try not to feed them.",
    "combat_enter|roasty|smug|Oh, a fight. This should be educational.",
    "combat_enter|roasty|surprised|Guns out already? Bold for you.",
    "combat_enter|roasty|laugh|You're in combat. Act like it for once.",
    "combat_enter|roasty|pout|Someone wants your inventory. Don't donate.",
    "combat_enter|roasty|evil|Fight mode. Please aim at them, not the floor.",
    "combat_enter|supportive|worried|You're in combat. Keep cover and track angles.",
    "combat_enter|supportive|fear|Fight started. Focus and don't overextend.",
    "combat_enter|supportive|neutral|Combat engaged. Watch flanks and reload timing.",
    "combat_enter|supportive|worried|Stay composed. Win the trade, then heal.",
    "combat_enter|supportive|smile|You've got this. Play smart, not loud.",
    "combat_enter|supportive|neutral|In combat. Prioritize info and positioning.",
    "combat_leave|roasty|smug|Combat over. Somehow you're still breathing.",
    "combat_leave|roasty|pout|Fight ended. Hide your celebration.",
    "combat_leave|roasty|laugh|Out of combat. Don't immediately dive back in.",
    "combat_leave|roasty|neutral|Threat gone. Check ammo before looting.",
    "combat_leave|supportive|happy|Combat cleared. Reset and heal up.",
    "combat_leave|supportive|smile|You're clear. Patch wounds and reload.",
    "combat_leave|supportive|neutral|Out of combat. Take a second to stabilize.",
    "combat_leave|supportive|happy|Nice. Use the downtime wisely.",
    "bleeding|roasty|disgusted|You're bleeding. Congrats on the leak.",
    "bleeding|roasty|pout|Bandage. Now. Your HP is dripping away.",
    "bleeding|roasty|worried|Bleed tick going. Medicine would be smart.",
    "bleeding|roasty|laugh|Red trail unlocked. Stealth is cancelled.",
    "bleeding|roasty|evil|Bleeding already? Peak efficiency.",
    "bleeding|supportive|worried|You're bleeding. Stop and bandage immediately.",
    "bleeding|supportive|fear|Bleed status active. Prioritize a medkit.",
    "bleeding|supportive|sad|Don't ignore the bleed. Fix it before fighting.",
    "bleeding|supportive|worried|Apply a bandage before you lose the fight to ticks.",
    "bleeding|supportive|neutral|Bleeding. Heal, then reassess.",
    "bleed_stopped|roasty|smug|Bleed stopped. Miracles do happen.",
    "bleed_stopped|roasty|smile|Finally patched. Try keeping the blood inside.",
    "bleed_stopped|roasty|neutral|Bleed cleared. Don't reopen it instantly.",
    "bleed_stopped|supportive|happy|Bleed stopped. Nice recovery.",
    "bleed_stopped|supportive|smile|You're sealed up. Stay careful.",
    "bleed_stopped|supportive|neutral|Bleeding resolved. Good timing.",
    "hunger_low|roasty|pout|You're starving. Eat something that isn't a bullet.",
    "hunger_low|roasty|disgusted|Hunger low. Your stomach is louder than your footsteps.",
    "hunger_low|roasty|smug|Hungry already? Professional scavenger energy.",
    "hunger_low|roasty|laugh|Food. Or keep roleplaying a skeleton.",
    "hunger_low|supportive|worried|Hunger is low. Find food before you weaken.",
    "hunger_low|supportive|neutral|Eat soon. Low hunger will punish you later.",
    "hunger_low|supportive|smile|Grab a snack when it's safe.",
    "hunger_low|supportive|worried|Hunger warning. Don't ignore it in a fight.",
    "thirst_low|roasty|pout|Thirsty? Water exists. Shocking, I know.",
    "thirst_low|roasty|disgusted|Your thirst bar is begging for help.",
    "thirst_low|roasty|smug|Dehydration speedrun, classic.",
    "thirst_low|roasty|laugh|Drink something. Sand is not hydration.",
    "thirst_low|supportive|worried|Thirst is low. Get water soon.",
    "thirst_low|supportive|neutral|Hydrate before you commit to another fight.",
    "thirst_low|supportive|smile|Find clean water when you can.",
    "thirst_low|supportive|worried|Low thirst will sneak up on you. Fix it.",
    "radiation|roasty|fear|Radiation. Glow-in-the-dark is not a flex.",
    "radiation|roasty|disgusted|You're cooking in rads. Leave. Immediately.",
    "radiation|roasty|worried|Radiation spike. Suit up or get out.",
    "radiation|roasty|evil|Rads rising. This is how people become lore.",
    "radiation|supportive|fear|Radiation detected. Exit the zone now.",
    "radiation|supportive|worried|You're taking rads. Find cleaner ground.",
    "radiation|supportive|neutral|Radiation active. Prioritize gear or escape.",
    "radiation|supportive|fear|Leave the radiation before it stacks.",
    "cold|roasty|pout|You're freezing. Find heat before you become a popsicle.",
    "cold|roasty|worried|Cold status. Campfire energy, please.",
    "cold|roasty|laugh|Shivering already? Tough guy.",
    "cold|roasty|smug|Temperature dropped. Fashion lost to survival.",
    "cold|supportive|worried|You're getting cold. Warm up soon.",
    "cold|supportive|neutral|Cold warning. Seek heat or warmer gear.",
    "cold|supportive|smile|Find a fire or shelter before it gets worse.",
    "cold|supportive|worried|Stay warm. Cold stacks will hurt.",
    "hot|roasty|disgusted|Overheating. Touch grass... preferably wet grass.",
    "hot|roasty|pout|Too hot. Cool down before you melt your braincell.",
    "hot|roasty|laugh|Heatstroke loading. Smart.",
    "hot|roasty|smug|You're cooking. Not in a cute way.",
    "hot|supportive|worried|You're overheating. Cool off soon.",
    "hot|supportive|neutral|Heat is high. Find shade or water.",
    "hot|supportive|smile|Cool down before committing to a long run.",
    "hot|supportive|worried|Hot status. Manage temperature now.",
    "drowning|roasty|fear|You're drowning. Surface. Now.",
    "drowning|roasty|surprised|Underwater panic hour?",
    "drowning|roasty|laugh|Air is free. Go get some.",
    "drowning|roasty|worried|Drowning. Swim up before this gets stupid.",
    "drowning|supportive|fear|You're drowning! Get to the surface!",
    "drowning|supportive|worried|Air is low. Break the water now.",
    "drowning|supportive|fear|Swim up. Don't fight under there.",
    "drowning|supportive|worried|Drowning status. Prioritize oxygen.",
    "staff_nearby|roasty|surprised|Staff nearby. Behave. Or at least pretend.",
    "staff_nearby|roasty|worried|Mod energy detected. Maybe hide the crimes.",
    "staff_nearby|roasty|smug|Staff in range. Your villain arc is postponed.",
    "staff_nearby|roasty|neutral|Admin proximity. Play nice.",
    "staff_nearby|supportive|worried|Staff nearby. Stay clean and careful.",
    "staff_nearby|supportive|neutral|A staff member is close. Keep it normal.",
    "staff_nearby|supportive|smile|Staff in the area. No funny business.",
    "staff_nearby|supportive|worried|Mod nearby. Focus on surviving, not flexing.",
    "enemy_nearby|roasty|evil|Hostile nearby. Smile for the crosshair.",
    "enemy_nearby|roasty|smug|Someone's close. Don't get caught looking AFK.",
    "enemy_nearby|roasty|surprised|Enemy in range. Ears up.",
    "enemy_nearby|roasty|laugh|Company. Hopefully not smarter than you.",
    "enemy_nearby|roasty|worried|Threat nearby. Check your corners.",
    "enemy_nearby|supportive|worried|Enemy nearby. Slow down and listen.",
    "enemy_nearby|supportive|fear|Hostile close. Ready your aim and cover.",
    "enemy_nearby|supportive|neutral|Someone's in your bubble. Stay alert.",
    "enemy_nearby|supportive|worried|Nearby threat. Don't sprint into them.",
    "enemy_nearby|supportive|smile|Keep composure. You can win this fight.",
    "party_join|roasty|smug|You're in a party. Try not to drag them down.",
    "party_join|roasty|laugh|Teammates acquired. Their mistake.",
    "party_join|roasty|pout|Party up. Share loot like an adult.",
    "party_join|roasty|evil|Squad formed. Chaos with friends.",
    "party_join|supportive|happy|Party joined. Stick together and callouts help.",
    "party_join|supportive|smile|You're teamed up. Watch each other's backs.",
    "party_join|supportive|neutral|In a party now. Share info and stay linked.",
    "party_join|supportive|happy|Nice. Team play wins more than ego.",
    "party_leave|roasty|pout|Party left. Solo queue dignity restored.",
    "party_leave|roasty|smug|Alone again. Just how your decision-making likes it.",
    "party_leave|roasty|neutral|Out of party. Don't get lonely and die.",
    "party_leave|supportive|neutral|You left the party. Stay aware solo.",
    "party_leave|supportive|worried|Solo now. Play safer angles.",
    "party_leave|supportive|smile|Party ended. You've got this alone too.",
    "reviving|roasty|smug|Look at you, being useful for once.",
    "reviving|roasty|smile|Reviving someone. Don't get beamed mid-animation.",
    "reviving|roasty|pout|Hero moment. Cover first, then the revive.",
    "reviving|roasty|laugh|Saving them? Bold charity.",
    "reviving|supportive|smile|Nice revive. Watch your surroundings while you do it.",
    "reviving|supportive|worried|Reviving. Keep an eye on flanks.",
    "reviving|supportive|happy|Good teammate play. Finish the revive safely.",
    "reviving|supportive|neutral|Hold the revive and stay ready to cancel if pushed.",
    "boss_spawn|roasty|evil|Boss event up. Go be brave. Or loot later. I don't care.",
    "boss_spawn|roasty|surprised|Big NPC online. Don't feed it for free.",
    "boss_spawn|roasty|smug|Event boss spotted. Try not to be the highlight reel.",
    "boss_spawn|roasty|laugh|World event. Perfect time for bad decisions.",
    "boss_spawn|roasty|neutral|Boss presence detected. Gear check.",
    "boss_spawn|supportive|surprised|A boss event is active. Prepare before engaging.",
    "boss_spawn|supportive|worried|Boss nearby or up. Watch the area carefully.",
    "boss_spawn|supportive|neutral|World boss event. Coordinate if you can.",
    "boss_spawn|supportive|smile|Event spawn. Opportunity if you're ready.",
    "boss_spawn|supportive|worried|Big threat event. Don't rush blind.",
    "timed_crate|roasty|smug|Timed crate. Race for loot, or race for death. Your call.",
    "timed_crate|roasty|evil|Crate timer up. Campers incoming.",
    "timed_crate|roasty|laugh|Timed crate. Perfect bait for greedy players.",
    "timed_crate|roasty|surprised|Crate event. Don't get third-partied mid-loot.",
    "timed_crate|roasty|pout|Go get shiny boxes. Try surviving the audience.",
    "timed_crate|supportive|happy|Timed crate is up. Approach carefully.",
    "timed_crate|supportive|worried|Crate event active. Check for campers first.",
    "timed_crate|supportive|neutral|Timed crate spotted. Plan your approach.",
    "timed_crate|supportive|smile|Good loot opportunity. Stay aware while opening.",
    "timed_crate|supportive|worried|Crate means contest. Don't tunnel vision.",
    "greeting|roasty|smug|April reporting in. Please be less tragic today.",
    "greeting|roasty|evil|Commentator online. Feed me mistakes.",
    "greeting|supportive|happy|April online. I've got your back.",
    "greeting|supportive|smile|Ready. Call me when it gets spicy.",
    "death|roasty|laugh|Dead again. Collectible achievement unlocked.",
    "death|supportive|sad|Down hard. Reset and come back smarter.",
    "respawn|roasty|smug|Respawned. Let's pretend that was intentional.",
    "respawn|supportive|happy|Fresh life. Start clean.",
    "downed|roasty|laugh|Horizontal again. Iconic.",
    "downed|supportive|worried|Downed. Crawl smart.",
    "safe_enter|roasty|smug|Safe zone. Even chaos needs a break.",
    "safe_leave|supportive|worried|Leaving safety. Eyes open.",
}

local DIALOGUE_RU = {
    "greeting|roasty|smug|O, ty menya vklyuchil? Ladno. Tolko ne pozor nas.",
    "greeting|roasty|pout|U menya byl normalnyy den, poka ty ne nazhal etot toggle.",
    "greeting|roasty|evil|Tvoy lichnyy commentator pribyl. Eto budet smeshno.",
    "greeting|roasty|laugh|Ya gotova. Day mne chto-to, nad chem mozhno porugat.",
    "greeting|roasty|neutral|April online. Ozhidaniya opasno nizkie.",
    "greeting|roasty|disgusted|Ty zval? Nadeyus, tvoy gameplay podros, poka menya ne bylo.",
    "greeting|supportive|smile|April online. Ya budu za toboy sledit.",
    "greeting|supportive|happy|Gotova, kogda ty gotov. Davay vyzhivem.",
    "greeting|supportive|neutral|Ya zdes. Bud na cheku - i vse budet ok.",
    "greeting|supportive|smile|Vse set! Postaraysya vernutsya v odnom kuske.",
    "greeting|supportive|happy|Tvoy lyubimyy announcer gotov k startu.",
    "greeting|supportive|neutral|Sistemy ready. Ya skazhu, esli chto-to vazhnoe.",
    "death|roasty|laugh|Ty otstoy, lol. Khochesh poprobovat snova?",
    "death|roasty|disgusted|Eto byl tvoy plan? Serezno?",
    "death|roasty|smug|Eshche odna tactical donation vragu.",
    "death|roasty|pout|Ya otvernulas na sekundu - i ty uzhe mertv.",
    "death|roasty|evil|Otlichnoe performance. Zero notes. Zero pulse tozhe.",
    "death|roasty|laugh|Speedrunish respawn screen snova?",
    "death|roasty|disgusted|Mozhet, puli promahnetsya, esli v sleduyushchiy raz postoyish eshche nepodvizhnee.",
    "death|roasty|smug|Khoroshie novosti: zemlya uspeshno tebya poymala.",
    "death|roasty|pout|Prekrati delat smert kak hobby.",
    "death|roasty|laugh|Oni dazhe ne napryaglis. Pochti impressive.",
    "death|roasty|evil|Bezuprechnaya demonstratsiya togo, kak ne nado.",
    "death|roasty|disgusted|Tvoi instincty vyzhivaniya podali v otstavku.",
    "death|roasty|smug|Ya videla training dummy s luchshim positioning.",
    "death|roasty|pout|Eta zhizn byla koroche, chem etot speech bubble.",
    "death|supportive|sad|Eto bylo bolno. Reset i medlennee.",
    "death|supportive|worried|Ty down, no eto ne konets. Uchish angle.",
    "death|supportive|smile|Plokhoy round. Fresh start.",
    "death|supportive|sad|Ne povezlo. Vernem v sleduyushchey zhizni.",
    "death|supportive|worried|Dysh. Podumay, chto tebya otkrylo.",
    "death|supportive|neutral|Death confirmed. Vremya menyat plan.",
    "death|supportive|smile|Otryasnis. Sleduyushchaya zhizn - tvoya.",
    "death|supportive|sad|Bylo zhestko, no teper ty znaesh, gde oni byli.",
    "death|supportive|worried|Razberi oshibku - i ostav ee pozadi.",
    "death|supportive|neutral|Odin plokhoy fight ne reshaet vsyu sessiyu.",
    "respawn|roasty|smug|Uzhe nazad? Poprobuy uderzhat eto telo hotya by minutku.",
    "respawn|roasty|pout|Novaya zhizn, te zhe somnitelnye decision-making.",
    "respawn|roasty|evil|Round two. Nu tochno nichego ne poydet ne tak.",
    "respawn|roasty|laugh|Knopka respawn zasluzhila overtime.",
    "respawn|roasty|neutral|S vozvrashcheniem. Ya sokhranila tvoyu dostoinstvo. Ego pochti ne bylo.",
    "respawn|roasty|smug|Fresh body dostavleno. Obrashchaysya chut berezhnee.",
    "respawn|roasty|pout|Ok, ne umirat srazu. Ves assignment na etom.",
    "respawn|roasty|laugh|Glyan, kto vybralsya s loading screen.",
    "respawn|supportive|happy|Ty vernulsya. Novaya zhizn, clean slate.",
    "respawn|supportive|smile|Respawned i ready. Ne toropis.",
    "respawn|supportive|neutral|Fresh start. Snachala check okrestnosti.",
    "respawn|supportive|happy|Vot i ty. Davay sdelaem etu zhizn znachimoy.",
    "respawn|supportive|smile|Snova v dele. Verni ritm.",
    "respawn|supportive|neutral|Respawn complete. Rebuild, prezhde chem brat fight.",
    "respawn|supportive|happy|Novaya zhizn ready. Nachni s bezopasnogo route.",
    "respawn|supportive|smile|S vozvrashcheniem. Po odnomu khoroshemu resheniyu za raz.",
    "downed|roasty|laugh|Inspektsiya pola idet khorosho?",
    "downed|roasty|smug|Ty nashel downed state. Ochen thorough testing.",
    "downed|roasty|pout|Crawl - eto ne combat strategy.",
    "downed|roasty|disgusted|Vot pochemu ya govorila ispolzovat cover.",
    "downed|roasty|evil|Technically zhiv. Emotionalno? Sporno.",
    "downed|roasty|laugh|Pomashi teammate snizu.",
    "downed|roasty|worried|Kto-nibud, revive etot professionalnyy pol-ornament.",
    "downed|roasty|smug|Vydayushchayasya poza. Ten out of ten.",
    "downed|supportive|worried|Ty downed. Za cover i zovi help.",
    "downed|supportive|fear|Derzhis nizko. Teammate eshche mozhet doyti.",
    "downed|supportive|sad|Ne sdavaysya. Polzi tuda, gde bezopasno.",
    "downed|supportive|worried|Downed, ne mertv. Break line of sight.",
    "downed|supportive|neutral|Ekonom movement i zhdi revive.",
    "downed|supportive|fear|Ostorozhno, eshche odin hit mozhet zakonchit.",
    "downed|supportive|sad|Polzi k cover, esli eto safe.",
    "downed|supportive|worried|Skazhi pozitsiyu i day team rabotat.",
    "revived|roasty|smug|Kto-to tebya realno podnyal. Bud blagodaren.",
    "revived|roasty|pout|Ty snova stoish. Sdelay tak, chtoby ono stoilo ih vremeni.",
    "revived|roasty|laugh|Revived! Pol budet skuchat.",
    "revived|roasty|evil|Second chance poluchen. Plokhie idei snova enabled.",
    "revived|roasty|neutral|Snova na nogah. Poprobuy ih ispolzovat v etot raz.",
    "revived|roasty|smug|U tvoego teammate neveroyatnaya vera v tebya.",
    "revived|supportive|happy|Ty up! Heal, prezhde chem re-engage.",
    "revived|supportive|smile|Nice recovery. Naydi cover i reset.",
    "revived|supportive|worried|Revived. Ne peek, poka ne healthy.",
    "revived|supportive|happy|Khoroshiy save. Teper derzhis s team.",
    "revived|supportive|neutral|Snova na nogah. Snachala stabilize.",
    "revived|supportive|smile|Second chance secured. Sdelay ego znachimym.",
    "low_health|roasty|worried|Tvoy health bar teper pochti decorative.",
    "low_health|roasty|pout|Odin chih - i ty snova na respawn.",
    "low_health|roasty|smug|Smelaya strategy: fight s trema pixelami HP.",
    "low_health|roasty|fear|Mozhet, hvatit peek? Prosto mysl.",
    "low_health|roasty|disgusted|Heal. Krasnyy screen - eto ne aesthetic.",
    "low_health|roasty|worried|Ty derzhishsya na confidence i plokhoy matematike.",
    "low_health|roasty|pout|Snachala naydi medicine, potom sleduyushchuyu pulyu.",
    "low_health|roasty|smug|Zhit na odnom hit point - eto ne personality.",
    "low_health|supportive|worried|Low health. Disengage i heal seychas.",
    "low_health|supportive|fear|Ty critical. Naydi hard cover.",
    "low_health|supportive|sad|Ne beri drugoy fight, poka ne vosstanovishsya.",
    "low_health|supportive|worried|Health nizkiy. Zamedlis i reset.",
    "low_health|supportive|neutral|Critical health. Priority - vyzhivanie.",
    "low_health|supportive|fear|Break line of sight i heal.",
    "low_health|supportive|worried|Seychas ne trade damage.",
    "low_health|supportive|neutral|Naydi bezopasnost, heal, potom pereotseni.",
    "recovered|roasty|smug|Health restored. Common sense eshche loading.",
    "recovered|roasty|smile|Patchnul - i gotov delat novye oshibki.",
    "recovered|roasty|laugh|Glyan-ka, ty otkryl healing.",
    "recovered|roasty|pout|Luchshe. Tolko ne trat eto srazu.",
    "recovered|roasty|evil|Polnee health bar, obnovlennyy capacity dlya haosa.",
    "recovered|roasty|neutral|Ty proshe medicine tutorial.",
    "recovered|supportive|happy|Health recovered. Ty snova ready.",
    "recovered|supportive|smile|Khoroshiy reset. Vybiray sleduyushchiy fight ostrozhno.",
    "recovered|supportive|neutral|Snova stable. Pereprover ammo i okrestnosti.",
    "recovered|supportive|happy|Nice recovery. Derzhi momentum.",
    "recovered|supportive|smile|Gorazdo luchshe. Ostavaysya disciplined.",
    "recovered|supportive|neutral|Recovery complete. Vozvrashchaysya, kogda timing pravilnyy.",
    "safe_enter|roasty|smug|Safe zone. Tut dazhe ty dolzhen vyzhit.",
    "safe_enter|roasty|laugh|Pozdravlyayu, igra teper tebya zashchishchaet.",
    "safe_enter|roasty|pout|Ty safe. Tolko ne spotknis ob nichego.",
    "safe_enter|roasty|neutral|Safe zone. Tvoi danger privileges vremenno otozvany.",
    "safe_enter|roasty|smile|Mirnaya minutka dlya tvoego overworked respawn key.",
    "safe_enter|roasty|evil|Naslazhdaysya safety, poka ona est.",
    "safe_enter|supportive|happy|Safe zone. Vozmi moment na reset.",
    "safe_enter|supportive|smile|Ty safe. Razberi inventar i planiruy dalshe.",
    "safe_enter|supportive|neutral|Safe zone. Horoshee vremya na regroup.",
    "safe_enter|supportive|happy|Dobralis safe. Restock, prezhde chem uhodit.",
    "safe_enter|supportive|smile|Tut ty protected. Ispolzuy breathing room.",
    "safe_enter|supportive|neutral|Prover, chto nuzhno, prezhde chem vykhodit.",
    "safe_leave|roasty|evil|Uezzhaesh iz safety? Eto budet entertaining.",
    "safe_leave|roasty|smug|Protection off. Posmotrim, skolko eto prodlitsya.",
    "safe_leave|roasty|pout|Obratno v danger bez vsyakogo supervision.",
    "safe_leave|roasty|laugh|Safe zone ostavlena. Respawn screen na dezhurstve.",
    "safe_leave|roasty|neutral|Ty snova vulnerable. Pritvoryaysya, chto ostorozhen.",
    "safe_leave|roasty|evil|I vot ushel tvoy posledniy khoroshiy excuse.",
    "safe_leave|supportive|worried|Vyhodish iz safe zone. Check route.",
    "safe_leave|supportive|neutral|Protection konchilas. Sledi za nearby players.",
    "safe_leave|supportive|smile|Snova snaruzhi. Dvizhaysya s purpose.",
    "safe_leave|supportive|worried|Ty snova exposed. Derzhi cover ryadom.",
    "safe_leave|supportive|neutral|Safe zone ostavlena. Sledi za okrestnostyami.",
    "safe_leave|supportive|smile|Route checked? Togda idem.",
    "combat_enter|roasty|evil|Combat start. Postaraysya ih ne feedit.",
    "combat_enter|roasty|smug|O, fight. Eto budet educational.",
    "combat_enter|roasty|surprised|Uzhe guns out? Smelo dlya tebya.",
    "combat_enter|roasty|laugh|Ty v combat. Khotya by raz povedi sebya sootvetstvenno.",
    "combat_enter|roasty|pout|Kto-to hochet tvoy inventar. Ne donate.",
    "combat_enter|roasty|evil|Fight mode. Please aim v nih, ne v pol.",
    "combat_enter|supportive|worried|Ty v combat. Derzhi cover i track angles.",
    "combat_enter|supportive|fear|Fight start. Focus i ne overextend.",
    "combat_enter|supportive|neutral|Combat engaged. Sledi flanks i reload timing.",
    "combat_enter|supportive|worried|Spokoyno. Vyigray trade, potom heal.",
    "combat_enter|supportive|smile|Ty spravishsya. Play smart, ne loud.",
    "combat_enter|supportive|neutral|V combat. Priority - info i positioning.",
    "combat_leave|roasty|smug|Combat over. Kak-to ty eshche dyshish.",
    "combat_leave|roasty|pout|Fight konchilsya. Spriach celebration.",
    "combat_leave|roasty|laugh|Out of combat. Ne nyryay obratno srazu.",
    "combat_leave|roasty|neutral|Threat ushel. Check ammo, prezhde chem loot.",
    "combat_leave|supportive|happy|Combat cleared. Reset i heal up.",
    "combat_leave|supportive|smile|Ty clear. Patch wounds i reload.",
    "combat_leave|supportive|neutral|Out of combat. Sekundu na stabilize.",
    "combat_leave|supportive|happy|Nice. Ispolzuy downtime umno.",
    "bleeding|roasty|disgusted|Ty bleeding. Congrats na utechku.",
    "bleeding|roasty|pout|Bandage. Seychas. Tvoy HP kapaet.",
    "bleeding|roasty|worried|Bleed tick idet. Medicine byla by smart.",
    "bleeding|roasty|laugh|Red trail unlocked. Stealth cancelled.",
    "bleeding|roasty|evil|Uzhe bleeding? Peak efficiency.",
    "bleeding|supportive|worried|Ty bleeding. Ostanovis i bandage srazu.",
    "bleeding|supportive|fear|Bleed status active. Priority - medkit.",
    "bleeding|supportive|sad|Ne ignoriruy bleed. Fix, prezhde chem fight.",
    "bleeding|supportive|worried|Kin bandage, poka ticks ne ubili fight.",
    "bleeding|supportive|neutral|Bleeding. Heal, potom pereotseni.",
    "bleed_stopped|roasty|smug|Bleed stopped. Chudesa byvayut.",
    "bleed_stopped|roasty|smile|Nakonets patched. Derzhi krov vnutri.",
    "bleed_stopped|roasty|neutral|Bleed cleared. Ne otkroy srazu snova.",
    "bleed_stopped|supportive|happy|Bleed stopped. Nice recovery.",
    "bleed_stopped|supportive|smile|Ty zapechatan. Bud ostorozhen.",
    "bleed_stopped|supportive|neutral|Bleeding resolved. Khoroshiy timing.",
    "hunger_low|roasty|pout|Ty golodayesh. Sesh chto-to, chto ne pulya.",
    "hunger_low|roasty|disgusted|Hunger low. Zheludok gromche footsteps.",
    "hunger_low|roasty|smug|Uzhe hungry? Professional scavenger energy.",
    "hunger_low|roasty|laugh|Food. Ili prodolzhay roleplay skeleton.",
    "hunger_low|supportive|worried|Hunger nizkiy. Naydi food, poka ne oslabel.",
    "hunger_low|supportive|neutral|Poesh skoro. Low hunger potom nakazhet.",
    "hunger_low|supportive|smile|Vozmi snack, kogda safe.",
    "hunger_low|supportive|worried|Hunger warning. Ne ignoriruy v fight.",
    "thirst_low|roasty|pout|Thirsty? Voda sushchestvuet. Shocking, ya znayu.",
    "thirst_low|roasty|disgusted|Tvoy thirst bar molit o help.",
    "thirst_low|roasty|smug|Dehydration speedrun, classic.",
    "thirst_low|roasty|laugh|Vypey chto-nibud. Pesok - eto ne hydration.",
    "thirst_low|supportive|worried|Thirst nizkiy. Voda skoro.",
    "thirst_low|supportive|neutral|Hydrate, prezhde chem brat drugoy fight.",
    "thirst_low|supportive|smile|Naydi clean water, kogda smozhesh.",
    "thirst_low|supportive|worried|Low thirst podkradetsya. Fix eto.",
    "radiation|roasty|fear|Radiation. Glow-in-the-dark - eto ne flex.",
    "radiation|roasty|disgusted|Ty zharishsya v rads. Vali. Immediately.",
    "radiation|roasty|worried|Radiation spike. Suit up ili vali.",
    "radiation|roasty|evil|Rads rastut. Tak lyudi stanovyatsya lore.",
    "radiation|supportive|fear|Radiation detected. Vali iz zone seychas.",
    "radiation|supportive|worried|Ty beresh rads. Naydi cleaner ground.",
    "radiation|supportive|neutral|Radiation active. Priority - gear ili escape.",
    "radiation|supportive|fear|Uydi ot radiation, poka ne stacks.",
    "cold|roasty|pout|Ty merznesh. Naydi heat, poka ne stal popsicle.",
    "cold|roasty|worried|Cold status. Campfire energy, please.",
    "cold|roasty|laugh|Uzhe drozhish? Tough guy.",
    "cold|roasty|smug|Temperature upala. Fashion proigral survival.",
    "cold|supportive|worried|Tebe holodno. Sogreysya skoro.",
    "cold|supportive|neutral|Cold warning. Ishchi heat ili teplee gear.",
    "cold|supportive|smile|Naydi fire ili shelter, poka ne khuzhe.",
    "cold|supportive|worried|Derzhi teplo. Cold stacks budut bolno.",
    "hot|roasty|disgusted|Overheating. Touch grass... zhelatelno mokryy grass.",
    "hot|roasty|pout|Slishkom hot. Cool down, poka ne rasplavil braincell.",
    "hot|roasty|laugh|Heatstroke loading. Smart.",
    "hot|roasty|smug|Ty zharishsya. Ne v cute smysle.",
    "hot|supportive|worried|Ty overheating. Cool off skoro.",
    "hot|supportive|neutral|Heat vysokiy. Naydi shade ili water.",
    "hot|supportive|smile|Cool down, prezhde chem long run.",
    "hot|supportive|worried|Hot status. Manage temperature seychas.",
    "drowning|roasty|fear|Ty drowning. Na poverhnost. Seychas.",
    "drowning|roasty|surprised|Underwater panic hour?",
    "drowning|roasty|laugh|Vozduh free. Idi vozmi.",
    "drowning|roasty|worried|Drowning. Plyvi vverh, poka ne stalo stupid.",
    "drowning|supportive|fear|Ty drowning! Na poverhnost!",
    "drowning|supportive|worried|Air nizkiy. Break water seychas.",
    "drowning|supportive|fear|Plyvi vverh. Ne fight tam vnizu.",
    "drowning|supportive|worried|Drowning status. Priority - oxygen.",
    "staff_nearby|roasty|surprised|Staff nearby. Behave. Ili hotya by pritvoryaysya.",
    "staff_nearby|roasty|worried|Mod energy detected. Mozhet, spryach crimes.",
    "staff_nearby|roasty|smug|Staff v range. Tvoy villain arc otlozhen.",
    "staff_nearby|roasty|neutral|Admin proximity. Play nice.",
    "staff_nearby|supportive|worried|Staff nearby. Bud clean i ostorozhen.",
    "staff_nearby|supportive|neutral|Staff member ryadom. Derzhi normalno.",
    "staff_nearby|supportive|smile|Staff v zone. Bez funny business.",
    "staff_nearby|supportive|worried|Mod nearby. Focus na survival, ne na flex.",
    "enemy_nearby|roasty|evil|Hostile nearby. Ulybnis dlya crosshair.",
    "enemy_nearby|roasty|smug|Kto-to blizko. Ne popadis looking AFK.",
    "enemy_nearby|roasty|surprised|Enemy v range. Ushi na cheku.",
    "enemy_nearby|roasty|laugh|Company. Nadeyus, ne umnee tebya.",
    "enemy_nearby|roasty|worried|Threat nearby. Check corners.",
    "enemy_nearby|supportive|worried|Enemy nearby. Zamedlis i slushay.",
    "enemy_nearby|supportive|fear|Hostile blizko. Gotov aim i cover.",
    "enemy_nearby|supportive|neutral|Kto-to v tvoem bubble. Stay alert.",
    "enemy_nearby|supportive|worried|Nearby threat. Ne sprint pryamo v nih.",
    "enemy_nearby|supportive|smile|Derzhi composure. Ty mozhesh vyigrat etot fight.",
    "party_join|roasty|smug|Ty v party. Postaraysya ih ne tyanut vniz.",
    "party_join|roasty|laugh|Teammates acquired. Ih oshibka.",
    "party_join|roasty|pout|Party up. Share loot kak adult.",
    "party_join|roasty|evil|Squad formed. Haos s friends.",
    "party_join|supportive|happy|Party joined. Derzhites vmeste - callouts pomogayut.",
    "party_join|supportive|smile|Vy v team. Sledite za spinyami drug druga.",
    "party_join|supportive|neutral|Teper v party. Share info i stay linked.",
    "party_join|supportive|happy|Nice. Team play byot ego.",
    "party_leave|roasty|pout|Party left. Solo queue dignity restored.",
    "party_leave|roasty|smug|Snova alone. Kak raz kak lyubit tvoe decision-making.",
    "party_leave|roasty|neutral|Out of party. Ne umri ot lonely.",
    "party_leave|supportive|neutral|Ty ushel iz party. Stay aware solo.",
    "party_leave|supportive|worried|Teper solo. Play safer angles.",
    "party_leave|supportive|smile|Party ended. Ty spravishsya i alone.",
    "reviving|roasty|smug|Glyan na tebya - useful hotya by raz.",
    "reviving|roasty|smile|Reviving kogo-to. Ne popadis beam mid-animation.",
    "reviving|roasty|pout|Hero moment. Snachala cover, potom revive.",
    "reviving|roasty|laugh|Spasaesh ih? Bold charity.",
    "reviving|supportive|smile|Nice revive. Sledi za okrestnostyami, poka delaesh.",
    "reviving|supportive|worried|Reviving. Sledi flanks.",
    "reviving|supportive|happy|Khoroshiy teammate play. Finish revive safe.",
    "reviving|supportive|neutral|Derzhi revive i bud gotov cancel, esli push.",
    "boss_spawn|roasty|evil|Boss event up. Idi bud brave. Ili loot potom. Mne vse ravno.",
    "boss_spawn|roasty|surprised|Big NPC online. Ne feedi ego za free.",
    "boss_spawn|roasty|smug|Event boss spotted. Postaraysya ne byt highlight reel.",
    "boss_spawn|roasty|laugh|World event. Idealnoe vremya dlya plohih resheniy.",
    "boss_spawn|roasty|neutral|Boss presence detected. Gear check.",
    "boss_spawn|supportive|surprised|Boss event active. Prepare, prezhde chem engage.",
    "boss_spawn|supportive|worried|Boss nearby ili up. Sledi za zonoy ostrozhno.",
    "boss_spawn|supportive|neutral|World boss event. Coordinate, esli mozhesh.",
    "boss_spawn|supportive|smile|Event spawn. Opportunity, esli ready.",
    "boss_spawn|supportive|worried|Big threat event. Ne rush blind.",
    "timed_crate|roasty|smug|Timed crate. Race za loot - ili race za death. Tvoy call.",
    "timed_crate|roasty|evil|Crate timer up. Campers incoming.",
    "timed_crate|roasty|laugh|Timed crate. Idealnyy bait dlya greedy players.",
    "timed_crate|roasty|surprised|Crate event. Ne popadis third-party mid-loot.",
    "timed_crate|roasty|pout|Idi za shiny boxes. Poprobuy vyzhit audience.",
    "timed_crate|supportive|happy|Timed crate up. Approach ostrozhno.",
    "timed_crate|supportive|worried|Crate event active. Snachala check campers.",
    "timed_crate|supportive|neutral|Timed crate spotted. Plan approach.",
    "timed_crate|supportive|smile|Khoroshiy loot opportunity. Stay aware, poka openish.",
    "timed_crate|supportive|worried|Crate = contest. Ne tunnel vision.",
    "greeting|roasty|smug|April na svyazi. Segodnya pomenishe tragic, please.",
    "greeting|roasty|evil|Commentator online. Kormi menya oshibkami.",
    "greeting|supportive|happy|April online. Ya za tebya.",
    "greeting|supportive|smile|Ready. Zovi, kogda stanet spicy.",
    "death|roasty|laugh|Snova dead. Collectible achievement unlocked.",
    "death|supportive|sad|Down hard. Reset i vernis umnee.",
    "respawn|roasty|smug|Respawned. Davay pritvorimsya, chto eto bylo intentional.",
    "respawn|supportive|happy|Fresh life. Start clean.",
    "downed|roasty|laugh|Snova horizontal. Iconic.",
    "downed|supportive|worried|Downed. Crawl umno.",
    "safe_enter|roasty|smug|Safe zone. Dazhe chaosu nuzhen break.",
    "safe_leave|supportive|worried|Uezzhaesh iz safety. Eyes open.",
}


local function add_line(target, line)
    local event, tone, expression, text =
        tostring(line):match("^([^|]+)|([^|]+)|([^|]+)|(.+)$")
    if not event then return end
    target[event] = target[event] or {}
    target[event][tone] = target[event][tone] or {}
    local pool = target[event][tone]
    pool[#pool + 1] = { expression, text }
end

local function load_lines(target, body)
    for k in pairs(target) do target[k] = nil end
    for line in tostring(body or ""):gmatch("[^\r\n]+") do
        add_line(target, line)
    end
end

H.dialogue_en = {}
H.dialogue_ru = {}
load_lines(H.dialogue_en, table.concat(DIALOGUE_EN, "\n"))
load_lines(H.dialogue_ru, table.concat(DIALOGUE_RU, "\n"))
-- Compat alias (English).
H.dialogue = H.dialogue_en
-- Vector shares April's line pools (same events / tones / wording).
V.dialogue_en = H.dialogue_en
V.dialogue_ru = H.dialogue_ru
V.dialogue = H.dialogue_en

local function fetch_dialogue(file_name)
    local fn = utility and (utility.http_get or utility.HttpGet)
    if type(fn) ~= "function" then return nil end
    local urls = {
        DIALOGUE_ROOT .. file_name,
        asset_urls.JSDELIVR_BASE .. "/anime/april/" .. file_name,
    }
    for _, url in ipairs(urls) do
        local ok, body, status = pcall(fn, url)
        if ok and type(body) == "string" and #body >= 100 then
            if status == nil or tonumber(status) == 200 then
                return body
            end
        end
    end
    return nil
end

function M.load_remote()
    local en_body = fetch_dialogue("dialogue.txt")
    if en_body then
        load_lines(H.dialogue_en, en_body)
        H.dialogue = H.dialogue_en
    end
    local ru_body = fetch_dialogue("dialogue_ru.txt")
    if ru_body then
        load_lines(H.dialogue_ru, ru_body)
    end
    return en_body ~= nil or ru_body ~= nil
end

function M.dialogue_for(character)
    character = character or H
    local ru = false
    pcall(function()
        ru = April.require("ui.i18n").is_ru() == true
    end)
    if ru and character.dialogue_ru and next(character.dialogue_ru) ~= nil then
        return character.dialogue_ru
    end
    return character.dialogue_en or character.dialogue or H.dialogue_en
end

M.characters = { H, V }
M.character_labels = { H.name, V.name }

function M.character(index)
    return M.characters[math.floor(tonumber(index) or 0) + 1] or H
end

return M
