local M = {}

M.by_id = {
    [1] = { name = "Wood Log", type = "Resource" },
    [2] = { name = "Bandage", type = "Tool" },
    [3] = { name = "Stone Hatchet", type = "Tool" },
    [4] = { name = "Heavy Ammo", type = "Ammo" },
    [5] = { name = "Salvaged AK47", type = "Gun" },
    [6] = { name = "Bottle Caps", type = "Resource" },
    [7] = { name = "Holo Sight", type = "Attachment" },
    [8] = { name = "Silencer", type = "Attachment" },
    [9] = { name = "Salvaged M14", type = "Gun" },
    [10] = { name = "Lighter", type = "Tool" },
    [11] = { name = "Swift Heavy Ammo", type = "Ammo" },
    [12] = { name = "Salvaged Sight", type = "Attachment" },
    [13] = { name = "Muzzle Boost", type = "Attachment" },
    [14] = { name = "Compensator", type = "Attachment" },
    [15] = { name = "Salvaged Lasersight", type = "Attachment" },
    [16] = { name = "Weapon Flashlight", type = "Attachment" },
    [17] = { name = "Salvaged Sniper Scope", type = "Attachment" },
    [18] = { name = "Military Sniper Scope", type = "Attachment" },
    [19] = { name = "Wooden Spear", type = "Tool" },
    [20] = { name = "Stone Spear", type = "Tool" },
    [21] = { name = "Stone Pickaxe", type = "Tool" },
    [22] = { name = "Crossbow", type = "Gun" },
    [23] = { name = "Wooden Bow", type = "Gun" },
    [24] = { name = "Cloth", type = "Resource" },
    [25] = { name = "Cactus Flesh", type = "Consumable" },
    [26] = { name = "Stone", type = "Resource" },
    [27] = { name = "Iron Ore", type = "Resource" },
    [28] = { name = "Quality Iron Ore", type = "Resource" },
    [29] = { name = "Campfire", type = "Bench" },
    [30] = { name = "Blueprint", type = "Tool" },
    [31] = { name = "Hammer", type = "Tool" },
    [32] = { name = "Raw Pork", type = "Consumable" },
    [33] = { name = "Cooked Pork", type = "Consumable" },
    [34] = { name = "Charcoal", type = "Resource" },
    [35] = { name = "Salvaged P250", type = "Gun" },
    [36] = { name = "Light Ammo", type = "Ammo" },
    [37] = { name = "Boulder", type = "Tool" },
    [38] = { name = "Salvaged SMG", type = "Gun" },
    [39] = { name = "Salvaged Python", type = "Gun" },
    [40] = { name = "Combustive Heavy Ammo", type = "Ammo" },
    [41] = { name = "Animal Fat", type = "Resource" },
    [42] = { name = "Small Storage Box", type = "Bench" },
    [43] = { name = "Raw Venison", type = "Consumable" },
    [44] = { name = "Cooked Venison", type = "Consumable" },
    [45] = { name = "Iron Shards", type = "Resource" },
    [46] = { name = "Steel Metal", type = "Resource" },
    [47] = { name = "Wooden Door", type = "Bench" },
    [48] = { name = "Wooden Lock", type = "Lock" },
    [49] = { name = "Combination Lock", type = "Lock" },
    [50] = { name = "Salvaged Metal Door", type = "Bench" },
    [51] = { name = "Base Cabinet", type = "Bench" },
    [52] = { name = "Wooden Double Door", type = "Bench" },
    [53] = { name = "Wooden Window Bars", type = "Bench" },
    [54] = { name = "Metal Window Bars", type = "Bench" },
    [55] = { name = "Glass Window", type = "Bench" },
    [56] = { name = "Steel Glass Window", type = "Bench" },
    [57] = { name = "Trap Door", type = "Bench" },
    [58] = { name = "Radiation Vitamins", type = "Consumable" },
    [59] = { name = "Hoodie", type = "Armor", armor_type = "Shirt" },
    [60] = { name = "Hazmat Suit", type = "Armor", armor_type = "All", attribute = "ResistWet" },
    [61] = { name = "Chicken MRE", type = "Consumable" },
    [62] = { name = "Beef MRE", type = "Consumable" },
    [63] = { name = "Pants", type = "Armor", armor_type = "Pants" },
    [64] = { name = "Phosphate Ore", type = "Resource" },
    [65] = { name = "Phosphate Dust", type = "Resource" },
    [66] = { name = "Leather", type = "Resource" },
    [67] = { name = "Furnace", type = "Bench" },
    [68] = { name = "Crude Fuel", type = "Resource" },
    [69] = { name = "Gunpowder", type = "Resource" },
    [70] = { name = "Bone Shards", type = "Resource" },
    [71] = { name = "Metal Door", type = "Bench" },
    [72] = { name = "Metal Double Door", type = "Bench" },
    [73] = { name = "Steel Door", type = "Bench" },
    [74] = { name = "Steel Double Door", type = "Bench" },
    [75] = { name = "Nail Gun", type = "Gun" },
    [76] = { name = "Steel Axe", type = "Tool" },
    [77] = { name = "Steel Pickaxe", type = "Tool" },
    [78] = { name = "Power Cell", type = "Misc" },
    [79] = { name = "Copper Cogs", type = "Misc" },
    [80] = { name = "Pipe", type = "Misc" },
    [81] = { name = "Propane Tank", type = "Misc" },
    [82] = { name = "Rope", type = "Misc" },
    [83] = { name = "Blade", type = "Misc" },
    [84] = { name = "Thread", type = "Misc" },
    [85] = { name = "Metal Plating", type = "Misc" },
    [86] = { name = "Spring", type = "Misc" },
    [87] = { name = "Tarp", type = "Misc" },
    [88] = { name = "Circuit Boards", type = "Misc" },
    [89] = { name = "Metal Scraps", type = "Misc" },
    [90] = { name = "Swift Light Ammo", type = "Ammo" },
    [91] = { name = "Sleeping Bag", type = "Bench" },
    [92] = { name = "Timed Charge", type = "Tool" },
    [93] = { name = "Nails", type = "Ammo" },
    [94] = { name = "Garage Door", type = "Bench" },
    [95] = { name = "Dynamite Bundle", type = "Tool" },
    [96] = { name = "Dynamite Stick", type = "Tool" },
    [97] = { name = "Salvaged RPG", type = "Gun" },
    [98] = { name = "Rocket", type = "Ammo" },
    [99] = { name = "Swift Rocket", type = "Ammo" },
    [100] = { name = "Combustive Rocket", type = "Ammo" },
    [101] = { name = "External Wooden Wall", type = "Bench" },
    [102] = { name = "External Wooden Gate", type = "Bench" },
    [103] = { name = "Vertical Window Cover", type = "Bench" },
    [104] = { name = "Horizontal Window Cover", type = "Bench" },
    [105] = { name = "Jail Wall", type = "Bench" },
    [106] = { name = "Jail Door", type = "Bench" },
    [107] = { name = "%s\\'s Trophy", type = "Bench" },
    [108] = { name = "Salvaged AK74u", type = "Gun" },
    [109] = { name = "Salvaged Pipe Rifle", type = "Gun" },
    [110] = { name = "Petroleum", type = "Resource" },
    [111] = { name = "Boots", type = "Armor", armor_type = "Boots" },
    [112] = { name = "Collared Shirt", type = "Armor", armor_type = "Shirt" },
    [113] = { name = "Shorts", type = "Armor", armor_type = "Pants" },
    [114] = { name = "Tank Top", type = "Armor", armor_type = "Shirt" },
    [115] = { name = "Cloth Shirt", type = "Armor", armor_type = "Shirt" },
    [116] = { name = "Cloth Pants", type = "Armor", armor_type = "Pants" },
    [117] = { name = "Cloth Footwraps", type = "Armor", armor_type = "Boots" },
    [118] = { name = "Leather Poncho", type = "Armor", armor_type = "Chestplate" },
    [119] = { name = "Leather Pants", type = "Armor", armor_type = "Pants" },
    [120] = { name = "Leather Shirt", type = "Armor", armor_type = "Shirt" },
    [121] = { name = "Leather Boots", type = "Armor", armor_type = "Boots" },
    [122] = { name = "Flannel Jacket", type = "Armor", armor_type = "Chestplate" },
    [123] = { name = "Wooden Helmet", type = "Armor", armor_type = "Hat" },
    [124] = { name = "Wooden Chestplate", type = "Armor", armor_type = "Chestplate" },
    [125] = { name = "Wooden Leggings", type = "Armor", armor_type = "Kilt" },
    [126] = { name = "Wooden Arrow", type = "Ammo" },
    [127] = { name = "Swift Arrow", type = "Ammo" },
    [128] = { name = "Bone Arrow", type = "Ammo" },
    [129] = { name = "Combustive Arrow", type = "Ammo" },
    [130] = { name = "Iron Shard Hatchet", type = "Tool" },
    [131] = { name = "Iron Shard Pickaxe", type = "Tool" },
    [132] = { name = "Large Furnace", type = "Bench" },
    [133] = { name = "Yellow Keycard", type = "Tool" },
    [134] = { name = "Purple Keycard", type = "Tool" },
    [135] = { name = "Pink Keycard", type = "Tool" },
    [136] = { name = "Small Medkit", type = "Tool" },
    [137] = { name = "Salvaged Break Action", type = "Gun" },
    [138] = { name = "Buckshot", type = "Ammo" },
    [139] = { name = "Slug", type = "Ammo" },
    [140] = { name = "Combustive Buckshot", type = "Ammo" },
    [141] = { name = "Steel Helmet", type = "Armor", armor_type = "Helmet" },
    [142] = { name = "Steel Chestplate", type = "Armor", armor_type = "Chestplate" },
    [143] = { name = "Steel Leggings", type = "Armor", armor_type = "Kilt" },
    [144] = { name = "Large Storage Box", type = "Bench" },
    [145] = { name = "Salvaged Helmet", type = "Armor", armor_type = "Helmet" },
    [146] = { name = "Salvaged Chestplate", type = "Armor", armor_type = "Chestplate" },
    [147] = { name = "Salvaged Leggings", type = "Armor", armor_type = "Kilt" },
    [148] = { name = "Military Helmet", type = "Armor", armor_type = "Helmet" },
    [149] = { name = "Military Chestplate", type = "Armor", armor_type = "Chestplate" },
    [150] = { name = "Military Leggings", type = "Armor", armor_type = "Kilt" },
    [151] = { name = "Hard Hat", type = "Armor", armor_type = "Hat" },
    [152] = { name = "Balaclava", type = "Armor", armor_type = "Face" },
    [153] = { name = "Cloth Headwrap", type = "Armor", armor_type = "Helmet" },
    [154] = { name = "Baseball Cap", type = "Armor", armor_type = "Hat" },
    [155] = { name = "Salvaged Gloves", type = "Armor", armor_type = "Gloves" },
    [156] = { name = "Cloth Handwraps", type = "Armor", armor_type = "Gloves" },
    [157] = { name = "Military Gloves", type = "Armor", armor_type = "Gloves" },
    [158] = { name = "Leather Gloves", type = "Armor", armor_type = "Gloves" },
    [159] = { name = "Wetsuit", type = "Armor", armor_type = "Wetsuit", attribute = "ResistWet" },
    [160] = { name = "Flippers", type = "Armor", armor_type = "Boots", attribute = "HasFlippers" },
    [161] = { name = "Diving Tank", type = "Armor", armor_type = "Chestplate", attribute = "HasTank" },
    [162] = { name = "Diving Goggles", type = "Armor", armor_type = "Helmet", attribute = "HasGoggles" },
    [163] = { name = "Cooking Pot", type = "Bench" },
    [164] = { name = "Ladder", type = "Bench" },
    [165] = { name = "Chocolate Bar", type = "Consumable" },
    [166] = { name = "Bean Can", type = "Consumable" },
    [167] = { name = "Meatball Can", type = "Consumable" },
    [168] = { name = "Fish Can", type = "Consumable" },
    [169] = { name = "Water Bottle", type = "Consumable" },
    [170] = { name = "Piercing Heavy Ammo", type = "Ammo" },
    [171] = { name = "Piercing Light Ammo", type = "Ammo" },
    [172] = { name = "Semi Receiver", type = "Misc" },
    [173] = { name = "SMG Receiver", type = "Misc" },
    [174] = { name = "Rifle Receiver", type = "Misc" },
    [175] = { name = "Steel Shovel", type = "Tool" },
    [176] = { name = "Empty Can", type = "Misc" },
    [177] = { name = "Care Package Signal", type = "Tool" },
    [178] = { name = "Duct Tape", type = "Misc" },
    [179] = { name = "Glue", type = "Misc" },
    [180] = { name = "Pistol Receiver", type = "Misc" },
    [181] = { name = "Salvaged Shovel", type = "Tool" },
    [182] = { name = "ez shovel", type = "Tool" },
    [183] = { name = "Anvil", type = "Bench" },
    [184] = { name = "Chemistry Lab", type = "Bench" },
    [185] = { name = "Carpentry Table", type = "Bench" },
    [186] = { name = "Sewing Table", type = "Bench" },
    [187] = { name = "Ammo Press", type = "Bench" },
    [188] = { name = "Culinary Table", type = "Bench" },
    [189] = { name = "Petroleum Refinery", type = "Bench" },
    [190] = { name = "Triangle Trap Door", type = "Bench" },
    [191] = { name = "Military AA12", type = "Gun" },
    [192] = { name = "Repair Table", type = "Bench" },
    [193] = { name = "Salvaged Pump Action", type = "Gun" },
    [194] = { name = "Bed", type = "Bench" },
    [195] = { name = "Wooden Spikes", type = "Bench" },
    [196] = { name = "Military ACOG Sight", type = "Attachment" },
    [197] = { name = "Metal Barricade", type = "Bench" },
    [198] = { name = "Military M4A1", type = "Gun" },
    [199] = { name = "Small Wooden Sign", type = "Bench" },
    [200] = { name = "Large Wooden Sign", type = "Bench" },
    [201] = { name = "Storage Cabinet", type = "Bench" },
    [202] = { name = "External Stone Gate", type = "Bench" },
    [203] = { name = "Bone Tool", type = "Tool" },
    [204] = { name = "Salvaged Skorpion", type = "Gun" },
    [205] = { name = "Candy Cane", type = "Tool" },
    [206] = { name = "Christmas Tree", type = "Bench" },
    [207] = { name = "Santa Hat", type = "Armor", armor_type = "Hat" },
    [208] = { name = "External Stone Wall", type = "Bench" },
    [209] = { name = "Blast Furnace", type = "Bench" },
    [210] = { name = "Military Barrett", type = "Gun" },
    [211] = { name = "Shotgun Turret", type = "Bench" },
    [212] = { name = "Military Grenade", type = "Tool" },
    [213] = { name = "Floor Grill", type = "Bench" },
    [214] = { name = "Bear Trap", type = "Bench" },
    [215] = { name = "Landmine Trap", type = "Bench" },
    [216] = { name = "Saw Bat", type = "Tool" },
    [217] = { name = "Machete", type = "Tool" },
    [218] = { name = "Military PKM", type = "Gun" },
    [219] = { name = "Bruno\\'s ACOG Sight", type = "Attachment" },
    [220] = { name = "Military Lasersight", type = "Attachment" },
    [221] = { name = "Bruno\\'s M4A1", type = "Gun" },
    [222] = { name = "Boss Chestplate", type = "Armor", armor_type = "Chestplate" },
    [223] = { name = "Boss Helmet", type = "Armor", armor_type = "Helmet" },
    [224] = { name = "Bunny Ears", type = "Armor", armor_type = "Hat" },
    [225] = { name = "Carrot Blade", type = "Tool" },
    [226] = { name = "Metal Spikes", type = "Bench" },
    [227] = { name = "Rug", type = "Bench" },
    [228] = { name = "Shop Machine", type = "Bench" },
    [229] = { name = "Chainsaw", type = "Tool" },
    [230] = { name = "Mining Drill", type = "Tool" },
    [231] = { name = "Extended Mag", type = "Attachment" },
    [232] = { name = "Jukebox", type = "Bench" },
    [233] = { name = "Wool Plant Seed", type = "Bench" },
    [234] = { name = "Wool", type = "Resource" },
    [235] = { name = "Loom", type = "Bench" },
    [236] = { name = "Small Planter Box", type = "Bench" },
    [237] = { name = "Large Planter Box", type = "Bench" },
    [238] = { name = "Tomato Plant Seed", type = "Bench" },
    [239] = { name = "Corn Plant Seed", type = "Bench" },
    [240] = { name = "Tomato", type = "Consumable" },
    [241] = { name = "Corn", type = "Consumable" },
    [242] = { name = "Chicken Egg", type = "Consumable" },
    [243] = { name = "Milk", type = "Consumable" },
    [244] = { name = "Raspberry Pie I", type = "Consumable" },
    [245] = { name = "Raspberry Pie II", type = "Consumable" },
    [246] = { name = "Raspberry Pie III", type = "Consumable" },
    [247] = { name = "Raspberry Pie IV", type = "Consumable" },
    [248] = { name = "Blueberry Pie I", type = "Consumable" },
    [249] = { name = "Blueberry Pie II", type = "Consumable" },
    [250] = { name = "Blueberry Pie III", type = "Consumable" },
    [251] = { name = "Blueberry Pie IV", type = "Consumable" },
    [252] = { name = "Lemon Cake I", type = "Consumable" },
    [253] = { name = "Lemon Cake II", type = "Consumable" },
    [254] = { name = "Lemon Cake III", type = "Consumable" },
    [255] = { name = "Lemon Cake IV", type = "Consumable" },
    [256] = { name = "Corn Bread I", type = "Consumable" },
    [257] = { name = "Corn Bread II", type = "Consumable" },
    [258] = { name = "Corn Bread III", type = "Consumable" },
    [259] = { name = "Corn Bread IV", type = "Consumable" },
    [260] = { name = "Cow Pasture", type = "Bench" },
    [261] = { name = "Chicken House", type = "Bench" },
    [262] = { name = "Barrel Light", type = "Bench" },
    [263] = { name = "Raspberries", type = "Consumable" },
    [264] = { name = "Blueberries", type = "Consumable" },
    [265] = { name = "Lemon", type = "Consumable" },
    [266] = { name = "Lemon Plant Seed", type = "Bench" },
    [267] = { name = "Raspberry Plant Seed", type = "Bench" },
    [268] = { name = "Blueberry Plant Seed", type = "Bench" },
    [269] = { name = "Military MP7", type = "Gun" },
    [270] = { name = "Red Keycard", type = "Tool" },
    [271] = { name = "Salvaged Double Barrel", type = "Gun" },
    [272] = { name = "Military Boat", type = "Resource" },
    [273] = { name = "Clan Table", type = "Bench" },
    [274] = { name = "Wooden Boat", type = "Resource" },
    [275] = { name = "Military USP", type = "Gun" },
    [276] = { name = "Common Goodie Bag", type = "Misc" },
    [277] = { name = "Rare Goodie Bag", type = "Misc" },
    [278] = { name = "Epic Goodie Bag", type = "Misc" },
    [279] = { name = "Candle", type = "Bench" },
    [280] = { name = "Armor Stand", type = "Bench" },
    [281] = { name = "Jack-O-Lantern", type = "Bench" },
    [282] = { name = "Small Cobweb", type = "Bench" },
    [283] = { name = "Large Cobweb", type = "Bench" },
    [284] = { name = "Pumpkin Plant Seed", type = "Bench" },
    [285] = { name = "Pumpkin", type = "ConsumableAmmoArmor", armor_type = "Helmet" },
    [286] = { name = "Halloween Scythe", type = "Tool" },
    [287] = { name = "Pumpkin Launcher", type = "Gun" },
    [288] = { name = "Raw Wolf", type = "Consumable" },
    [289] = { name = "Cooked Wolf", type = "Consumable" },
    [290] = { name = "Pumpkin Pie", type = "Consumable" },
    [291] = { name = "Cursed Pumpkin", type = "Ammo" },
    [292] = { name = "Marsh Bar", type = "Consumable" },
    [293] = { name = "Peanut Butter Cup", type = "Consumable" },
    [294] = { name = "Candy Roll", type = "Consumable" },
    [295] = { name = "Scarecrow", type = "Bench" },
    [296] = { name = "Salvaged Shotgun", type = "Gun" },
    [297] = { name = "Salvaged Shell", type = "Ammo" },
    [298] = { name = "Bone Armor", type = "Armor", armor_type = "All" },
    [299] = { name = "Armor Plate", type = "Attachment" },
    [300] = { name = "Heavy Padding", type = "Attachment" },
    [301] = { name = "Night Vision Goggles", type = "Attachment", attribute = "NVG" },
    [302] = { name = "Lightweight Padding", type = "Attachment", attribute = "SilentSteps" },
    [303] = { name = "Resistant Rubber", type = "Attachment" },
    [304] = { name = "Armor Polish", type = "Attachment" },
    [305] = { name = "Water Filter", type = "Attachment", attribute = "WaterFilter" },
    [306] = { name = "Steel Toes", type = "Attachment", attribute = "SteelToes" },
    [307] = { name = "Snorkle", type = "Attachment", attribute = "Snorkle" },
    [308] = { name = "Military Backpack", type = "Backpack" },
    [309] = { name = "Salvaged Backpack", type = "Backpack" },
    [310] = { name = "Salvaged Sniper", type = "Gun" },
    [311] = { name = "Military Grenade Launcher", type = "Gun" },
    [312] = { name = "Explosive Shell", type = "Ammo" },
    [313] = { name = "Salvaged Flycopter", type = "Resource" },
    [314] = { name = "Fireplace", type = "Bench" },
    [315] = { name = "Black Keycard", type = "Tool" },
    [316] = { name = "Salvaged Grenade Launcher", type = "Gun" },
    [317] = { name = "Salvaged Explosive Shell", type = "Ammo" },
    [318] = { name = "Shotgun Shell", type = "Ammo" },
    [319] = { name = "Large Medkit", type = "Consumable" },
    [320] = { name = "Small Battery", type = "Bench" },
    [321] = { name = "Medium Battery", type = "Bench" },
    [322] = { name = "Large Battery", type = "Bench" },
    [323] = { name = "Crude Fuel Generator", type = "Bench" },
    [324] = { name = "Solar Panel", type = "Bench" },
    [325] = { name = "Water Turbine", type = "Bench" },
    [326] = { name = "Wire Cutters", type = "Tool" },
    [327] = { name = "Button", type = "Bench" },
    [328] = { name = "Electric Furnace", type = "Bench" },
    [329] = { name = "Electric Heater", type = "Bench" },
    [330] = { name = "Switch", type = "Bench" },
    [331] = { name = "Windmill", type = "Bench" },
    [332] = { name = "Splitter", type = "Bench" },
    [333] = { name = "Military Boat", type = "Resource" },
    [334] = { name = "Auto Turret", type = "Bench" },
    [335] = { name = "Military M39", type = "Gun" },
    [336] = { name = "White Ornament", type = "Resource" },
    [337] = { name = "Red Ornament", type = "Resource" },
    [338] = { name = "Purple Ornament", type = "Resource" },
    [339] = { name = "Wreath", type = "Bench" },
    [340] = { name = "Christmas Lights", type = "Bench" },
    [341] = { name = "Admin Tool", type = "Tool" },
}

M.by_attribute = {
    ["HasFlippers"] = "Flippers",
    ["HasGoggles"] = "Diving Goggles",
    ["HasTank"] = "Diving Tank",
    ["NVG"] = "Night Vision Goggles",
    ["ResistWet"] = "Wetsuit",
    ["SilentSteps"] = "Lightweight Padding",
    ["Snorkle"] = "Snorkle",
    ["SteelToes"] = "Steel Toes",
    ["WaterFilter"] = "Water Filter",
}

M.by_name = {
    ["Wood Log"] = { id = 1, type = "Resource" },
    ["Bandage"] = { id = 2, type = "Tool" },
    ["Stone Hatchet"] = { id = 3, type = "Tool" },
    ["Heavy Ammo"] = { id = 4, type = "Ammo" },
    ["Salvaged AK47"] = { id = 5, type = "Gun" },
    ["Bottle Caps"] = { id = 6, type = "Resource" },
    ["Holo Sight"] = { id = 7, type = "Attachment" },
    ["Silencer"] = { id = 8, type = "Attachment" },
    ["Salvaged M14"] = { id = 9, type = "Gun" },
    ["Lighter"] = { id = 10, type = "Tool" },
    ["Swift Heavy Ammo"] = { id = 11, type = "Ammo" },
    ["Salvaged Sight"] = { id = 12, type = "Attachment" },
    ["Muzzle Boost"] = { id = 13, type = "Attachment" },
    ["Compensator"] = { id = 14, type = "Attachment" },
    ["Salvaged Lasersight"] = { id = 15, type = "Attachment" },
    ["Weapon Flashlight"] = { id = 16, type = "Attachment" },
    ["Salvaged Sniper Scope"] = { id = 17, type = "Attachment" },
    ["Military Sniper Scope"] = { id = 18, type = "Attachment" },
    ["Wooden Spear"] = { id = 19, type = "Tool" },
    ["Stone Spear"] = { id = 20, type = "Tool" },
    ["Stone Pickaxe"] = { id = 21, type = "Tool" },
    ["Crossbow"] = { id = 22, type = "Gun" },
    ["Wooden Bow"] = { id = 23, type = "Gun" },
    ["Cloth"] = { id = 24, type = "Resource" },
    ["Cactus Flesh"] = { id = 25, type = "Consumable" },
    ["Stone"] = { id = 26, type = "Resource" },
    ["Iron Ore"] = { id = 27, type = "Resource" },
    ["Quality Iron Ore"] = { id = 28, type = "Resource" },
    ["Campfire"] = { id = 29, type = "Bench" },
    ["Blueprint"] = { id = 30, type = "Tool" },
    ["Hammer"] = { id = 31, type = "Tool" },
    ["Raw Pork"] = { id = 32, type = "Consumable" },
    ["Cooked Pork"] = { id = 33, type = "Consumable" },
    ["Charcoal"] = { id = 34, type = "Resource" },
    ["Salvaged P250"] = { id = 35, type = "Gun" },
    ["Light Ammo"] = { id = 36, type = "Ammo" },
    ["Boulder"] = { id = 37, type = "Tool" },
    ["Salvaged SMG"] = { id = 38, type = "Gun" },
    ["Salvaged Python"] = { id = 39, type = "Gun" },
    ["Combustive Heavy Ammo"] = { id = 40, type = "Ammo" },
    ["Animal Fat"] = { id = 41, type = "Resource" },
    ["Small Storage Box"] = { id = 42, type = "Bench" },
    ["Raw Venison"] = { id = 43, type = "Consumable" },
    ["Cooked Venison"] = { id = 44, type = "Consumable" },
    ["Iron Shards"] = { id = 45, type = "Resource" },
    ["Steel Metal"] = { id = 46, type = "Resource" },
    ["Wooden Door"] = { id = 47, type = "Bench" },
    ["Wooden Lock"] = { id = 48, type = "Lock" },
    ["Combination Lock"] = { id = 49, type = "Lock" },
    ["Salvaged Metal Door"] = { id = 50, type = "Bench" },
    ["Base Cabinet"] = { id = 51, type = "Bench" },
    ["Wooden Double Door"] = { id = 52, type = "Bench" },
    ["Wooden Window Bars"] = { id = 53, type = "Bench" },
    ["Metal Window Bars"] = { id = 54, type = "Bench" },
    ["Glass Window"] = { id = 55, type = "Bench" },
    ["Steel Glass Window"] = { id = 56, type = "Bench" },
    ["Trap Door"] = { id = 57, type = "Bench" },
    ["Radiation Vitamins"] = { id = 58, type = "Consumable" },
    ["Hoodie"] = { id = 59, type = "Armor", armor_type = "Shirt" },
    ["Hazmat Suit"] = { id = 60, type = "Armor", armor_type = "All", attribute = "ResistWet" },
    ["Chicken MRE"] = { id = 61, type = "Consumable" },
    ["Beef MRE"] = { id = 62, type = "Consumable" },
    ["Pants"] = { id = 63, type = "Armor", armor_type = "Pants" },
    ["Phosphate Ore"] = { id = 64, type = "Resource" },
    ["Phosphate Dust"] = { id = 65, type = "Resource" },
    ["Leather"] = { id = 66, type = "Resource" },
    ["Furnace"] = { id = 67, type = "Bench" },
    ["Crude Fuel"] = { id = 68, type = "Resource" },
    ["Gunpowder"] = { id = 69, type = "Resource" },
    ["Bone Shards"] = { id = 70, type = "Resource" },
    ["Metal Door"] = { id = 71, type = "Bench" },
    ["Metal Double Door"] = { id = 72, type = "Bench" },
    ["Steel Door"] = { id = 73, type = "Bench" },
    ["Steel Double Door"] = { id = 74, type = "Bench" },
    ["Nail Gun"] = { id = 75, type = "Gun" },
    ["Steel Axe"] = { id = 76, type = "Tool" },
    ["Steel Pickaxe"] = { id = 77, type = "Tool" },
    ["Power Cell"] = { id = 78, type = "Misc" },
    ["Copper Cogs"] = { id = 79, type = "Misc" },
    ["Pipe"] = { id = 80, type = "Misc" },
    ["Propane Tank"] = { id = 81, type = "Misc" },
    ["Rope"] = { id = 82, type = "Misc" },
    ["Blade"] = { id = 83, type = "Misc" },
    ["Thread"] = { id = 84, type = "Misc" },
    ["Metal Plating"] = { id = 85, type = "Misc" },
    ["Spring"] = { id = 86, type = "Misc" },
    ["Tarp"] = { id = 87, type = "Misc" },
    ["Circuit Boards"] = { id = 88, type = "Misc" },
    ["Metal Scraps"] = { id = 89, type = "Misc" },
    ["Swift Light Ammo"] = { id = 90, type = "Ammo" },
    ["Sleeping Bag"] = { id = 91, type = "Bench" },
    ["Timed Charge"] = { id = 92, type = "Tool" },
    ["Nails"] = { id = 93, type = "Ammo" },
    ["Garage Door"] = { id = 94, type = "Bench" },
    ["Dynamite Bundle"] = { id = 95, type = "Tool" },
    ["Dynamite Stick"] = { id = 96, type = "Tool" },
    ["Salvaged RPG"] = { id = 97, type = "Gun" },
    ["Rocket"] = { id = 98, type = "Ammo" },
    ["Swift Rocket"] = { id = 99, type = "Ammo" },
    ["Combustive Rocket"] = { id = 100, type = "Ammo" },
    ["External Wooden Wall"] = { id = 101, type = "Bench" },
    ["External Wooden Gate"] = { id = 102, type = "Bench" },
    ["Vertical Window Cover"] = { id = 103, type = "Bench" },
    ["Horizontal Window Cover"] = { id = 104, type = "Bench" },
    ["Jail Wall"] = { id = 105, type = "Bench" },
    ["Jail Door"] = { id = 106, type = "Bench" },
    ["%s\\'s Trophy"] = { id = 107, type = "Bench" },
    ["Salvaged AK74u"] = { id = 108, type = "Gun" },
    ["Salvaged Pipe Rifle"] = { id = 109, type = "Gun" },
    ["Petroleum"] = { id = 110, type = "Resource" },
    ["Boots"] = { id = 111, type = "Armor", armor_type = "Boots" },
    ["Collared Shirt"] = { id = 112, type = "Armor", armor_type = "Shirt" },
    ["Shorts"] = { id = 113, type = "Armor", armor_type = "Pants" },
    ["Tank Top"] = { id = 114, type = "Armor", armor_type = "Shirt" },
    ["Cloth Shirt"] = { id = 115, type = "Armor", armor_type = "Shirt" },
    ["Cloth Pants"] = { id = 116, type = "Armor", armor_type = "Pants" },
    ["Cloth Footwraps"] = { id = 117, type = "Armor", armor_type = "Boots" },
    ["Leather Poncho"] = { id = 118, type = "Armor", armor_type = "Chestplate" },
    ["Leather Pants"] = { id = 119, type = "Armor", armor_type = "Pants" },
    ["Leather Shirt"] = { id = 120, type = "Armor", armor_type = "Shirt" },
    ["Leather Boots"] = { id = 121, type = "Armor", armor_type = "Boots" },
    ["Flannel Jacket"] = { id = 122, type = "Armor", armor_type = "Chestplate" },
    ["Wooden Helmet"] = { id = 123, type = "Armor", armor_type = "Hat" },
    ["Wooden Chestplate"] = { id = 124, type = "Armor", armor_type = "Chestplate" },
    ["Wooden Leggings"] = { id = 125, type = "Armor", armor_type = "Kilt" },
    ["Wooden Arrow"] = { id = 126, type = "Ammo" },
    ["Swift Arrow"] = { id = 127, type = "Ammo" },
    ["Bone Arrow"] = { id = 128, type = "Ammo" },
    ["Combustive Arrow"] = { id = 129, type = "Ammo" },
    ["Iron Shard Hatchet"] = { id = 130, type = "Tool" },
    ["Iron Shard Pickaxe"] = { id = 131, type = "Tool" },
    ["Large Furnace"] = { id = 132, type = "Bench" },
    ["Yellow Keycard"] = { id = 133, type = "Tool" },
    ["Purple Keycard"] = { id = 134, type = "Tool" },
    ["Pink Keycard"] = { id = 135, type = "Tool" },
    ["Small Medkit"] = { id = 136, type = "Tool" },
    ["Salvaged Break Action"] = { id = 137, type = "Gun" },
    ["Buckshot"] = { id = 138, type = "Ammo" },
    ["Slug"] = { id = 139, type = "Ammo" },
    ["Combustive Buckshot"] = { id = 140, type = "Ammo" },
    ["Steel Helmet"] = { id = 141, type = "Armor", armor_type = "Helmet" },
    ["Steel Chestplate"] = { id = 142, type = "Armor", armor_type = "Chestplate" },
    ["Steel Leggings"] = { id = 143, type = "Armor", armor_type = "Kilt" },
    ["Large Storage Box"] = { id = 144, type = "Bench" },
    ["Salvaged Helmet"] = { id = 145, type = "Armor", armor_type = "Helmet" },
    ["Salvaged Chestplate"] = { id = 146, type = "Armor", armor_type = "Chestplate" },
    ["Salvaged Leggings"] = { id = 147, type = "Armor", armor_type = "Kilt" },
    ["Military Helmet"] = { id = 148, type = "Armor", armor_type = "Helmet" },
    ["Military Chestplate"] = { id = 149, type = "Armor", armor_type = "Chestplate" },
    ["Military Leggings"] = { id = 150, type = "Armor", armor_type = "Kilt" },
    ["Hard Hat"] = { id = 151, type = "Armor", armor_type = "Hat" },
    ["Balaclava"] = { id = 152, type = "Armor", armor_type = "Face" },
    ["Cloth Headwrap"] = { id = 153, type = "Armor", armor_type = "Helmet" },
    ["Baseball Cap"] = { id = 154, type = "Armor", armor_type = "Hat" },
    ["Salvaged Gloves"] = { id = 155, type = "Armor", armor_type = "Gloves" },
    ["Cloth Handwraps"] = { id = 156, type = "Armor", armor_type = "Gloves" },
    ["Military Gloves"] = { id = 157, type = "Armor", armor_type = "Gloves" },
    ["Leather Gloves"] = { id = 158, type = "Armor", armor_type = "Gloves" },
    ["Wetsuit"] = { id = 159, type = "Armor", armor_type = "Wetsuit", attribute = "ResistWet" },
    ["Flippers"] = { id = 160, type = "Armor", armor_type = "Boots", attribute = "HasFlippers" },
    ["Diving Tank"] = { id = 161, type = "Armor", armor_type = "Chestplate", attribute = "HasTank" },
    ["Diving Goggles"] = { id = 162, type = "Armor", armor_type = "Helmet", attribute = "HasGoggles" },
    ["Cooking Pot"] = { id = 163, type = "Bench" },
    ["Ladder"] = { id = 164, type = "Bench" },
    ["Chocolate Bar"] = { id = 165, type = "Consumable" },
    ["Bean Can"] = { id = 166, type = "Consumable" },
    ["Meatball Can"] = { id = 167, type = "Consumable" },
    ["Fish Can"] = { id = 168, type = "Consumable" },
    ["Water Bottle"] = { id = 169, type = "Consumable" },
    ["Piercing Heavy Ammo"] = { id = 170, type = "Ammo" },
    ["Piercing Light Ammo"] = { id = 171, type = "Ammo" },
    ["Semi Receiver"] = { id = 172, type = "Misc" },
    ["SMG Receiver"] = { id = 173, type = "Misc" },
    ["Rifle Receiver"] = { id = 174, type = "Misc" },
    ["Steel Shovel"] = { id = 175, type = "Tool" },
    ["Empty Can"] = { id = 176, type = "Misc" },
    ["Care Package Signal"] = { id = 177, type = "Tool" },
    ["Duct Tape"] = { id = 178, type = "Misc" },
    ["Glue"] = { id = 179, type = "Misc" },
    ["Pistol Receiver"] = { id = 180, type = "Misc" },
    ["Salvaged Shovel"] = { id = 181, type = "Tool" },
    ["ez shovel"] = { id = 182, type = "Tool" },
    ["Anvil"] = { id = 183, type = "Bench" },
    ["Chemistry Lab"] = { id = 184, type = "Bench" },
    ["Carpentry Table"] = { id = 185, type = "Bench" },
    ["Sewing Table"] = { id = 186, type = "Bench" },
    ["Ammo Press"] = { id = 187, type = "Bench" },
    ["Culinary Table"] = { id = 188, type = "Bench" },
    ["Petroleum Refinery"] = { id = 189, type = "Bench" },
    ["Triangle Trap Door"] = { id = 190, type = "Bench" },
    ["Military AA12"] = { id = 191, type = "Gun" },
    ["Repair Table"] = { id = 192, type = "Bench" },
    ["Salvaged Pump Action"] = { id = 193, type = "Gun" },
    ["Bed"] = { id = 194, type = "Bench" },
    ["Wooden Spikes"] = { id = 195, type = "Bench" },
    ["Military ACOG Sight"] = { id = 196, type = "Attachment" },
    ["Metal Barricade"] = { id = 197, type = "Bench" },
    ["Military M4A1"] = { id = 198, type = "Gun" },
    ["Small Wooden Sign"] = { id = 199, type = "Bench" },
    ["Large Wooden Sign"] = { id = 200, type = "Bench" },
    ["Storage Cabinet"] = { id = 201, type = "Bench" },
    ["External Stone Gate"] = { id = 202, type = "Bench" },
    ["Bone Tool"] = { id = 203, type = "Tool" },
    ["Salvaged Skorpion"] = { id = 204, type = "Gun" },
    ["Candy Cane"] = { id = 205, type = "Tool" },
    ["Christmas Tree"] = { id = 206, type = "Bench" },
    ["Santa Hat"] = { id = 207, type = "Armor", armor_type = "Hat" },
    ["External Stone Wall"] = { id = 208, type = "Bench" },
    ["Blast Furnace"] = { id = 209, type = "Bench" },
    ["Military Barrett"] = { id = 210, type = "Gun" },
    ["Shotgun Turret"] = { id = 211, type = "Bench" },
    ["Military Grenade"] = { id = 212, type = "Tool" },
    ["Floor Grill"] = { id = 213, type = "Bench" },
    ["Bear Trap"] = { id = 214, type = "Bench" },
    ["Landmine Trap"] = { id = 215, type = "Bench" },
    ["Saw Bat"] = { id = 216, type = "Tool" },
    ["Machete"] = { id = 217, type = "Tool" },
    ["Military PKM"] = { id = 218, type = "Gun" },
    ["Bruno\\'s ACOG Sight"] = { id = 219, type = "Attachment" },
    ["Military Lasersight"] = { id = 220, type = "Attachment" },
    ["Bruno\\'s M4A1"] = { id = 221, type = "Gun" },
    ["Boss Chestplate"] = { id = 222, type = "Armor", armor_type = "Chestplate" },
    ["Boss Helmet"] = { id = 223, type = "Armor", armor_type = "Helmet" },
    ["Bunny Ears"] = { id = 224, type = "Armor", armor_type = "Hat" },
    ["Carrot Blade"] = { id = 225, type = "Tool" },
    ["Metal Spikes"] = { id = 226, type = "Bench" },
    ["Rug"] = { id = 227, type = "Bench" },
    ["Shop Machine"] = { id = 228, type = "Bench" },
    ["Chainsaw"] = { id = 229, type = "Tool" },
    ["Mining Drill"] = { id = 230, type = "Tool" },
    ["Extended Mag"] = { id = 231, type = "Attachment" },
    ["Jukebox"] = { id = 232, type = "Bench" },
    ["Wool Plant Seed"] = { id = 233, type = "Bench" },
    ["Wool"] = { id = 234, type = "Resource" },
    ["Loom"] = { id = 235, type = "Bench" },
    ["Small Planter Box"] = { id = 236, type = "Bench" },
    ["Large Planter Box"] = { id = 237, type = "Bench" },
    ["Tomato Plant Seed"] = { id = 238, type = "Bench" },
    ["Corn Plant Seed"] = { id = 239, type = "Bench" },
    ["Tomato"] = { id = 240, type = "Consumable" },
    ["Corn"] = { id = 241, type = "Consumable" },
    ["Chicken Egg"] = { id = 242, type = "Consumable" },
    ["Milk"] = { id = 243, type = "Consumable" },
    ["Raspberry Pie I"] = { id = 244, type = "Consumable" },
    ["Raspberry Pie II"] = { id = 245, type = "Consumable" },
    ["Raspberry Pie III"] = { id = 246, type = "Consumable" },
    ["Raspberry Pie IV"] = { id = 247, type = "Consumable" },
    ["Blueberry Pie I"] = { id = 248, type = "Consumable" },
    ["Blueberry Pie II"] = { id = 249, type = "Consumable" },
    ["Blueberry Pie III"] = { id = 250, type = "Consumable" },
    ["Blueberry Pie IV"] = { id = 251, type = "Consumable" },
    ["Lemon Cake I"] = { id = 252, type = "Consumable" },
    ["Lemon Cake II"] = { id = 253, type = "Consumable" },
    ["Lemon Cake III"] = { id = 254, type = "Consumable" },
    ["Lemon Cake IV"] = { id = 255, type = "Consumable" },
    ["Corn Bread I"] = { id = 256, type = "Consumable" },
    ["Corn Bread II"] = { id = 257, type = "Consumable" },
    ["Corn Bread III"] = { id = 258, type = "Consumable" },
    ["Corn Bread IV"] = { id = 259, type = "Consumable" },
    ["Cow Pasture"] = { id = 260, type = "Bench" },
    ["Chicken House"] = { id = 261, type = "Bench" },
    ["Barrel Light"] = { id = 262, type = "Bench" },
    ["Raspberries"] = { id = 263, type = "Consumable" },
    ["Blueberries"] = { id = 264, type = "Consumable" },
    ["Lemon"] = { id = 265, type = "Consumable" },
    ["Lemon Plant Seed"] = { id = 266, type = "Bench" },
    ["Raspberry Plant Seed"] = { id = 267, type = "Bench" },
    ["Blueberry Plant Seed"] = { id = 268, type = "Bench" },
    ["Military MP7"] = { id = 269, type = "Gun" },
    ["Red Keycard"] = { id = 270, type = "Tool" },
    ["Salvaged Double Barrel"] = { id = 271, type = "Gun" },
    ["Military Boat"] = { id = 272, type = "Resource" },
    ["Clan Table"] = { id = 273, type = "Bench" },
    ["Wooden Boat"] = { id = 274, type = "Resource" },
    ["Military USP"] = { id = 275, type = "Gun" },
    ["Common Goodie Bag"] = { id = 276, type = "Misc" },
    ["Rare Goodie Bag"] = { id = 277, type = "Misc" },
    ["Epic Goodie Bag"] = { id = 278, type = "Misc" },
    ["Candle"] = { id = 279, type = "Bench" },
    ["Armor Stand"] = { id = 280, type = "Bench" },
    ["Jack-O-Lantern"] = { id = 281, type = "Bench" },
    ["Small Cobweb"] = { id = 282, type = "Bench" },
    ["Large Cobweb"] = { id = 283, type = "Bench" },
    ["Pumpkin Plant Seed"] = { id = 284, type = "Bench" },
    ["Pumpkin"] = { id = 285, type = "ConsumableAmmoArmor", armor_type = "Helmet" },
    ["Halloween Scythe"] = { id = 286, type = "Tool" },
    ["Pumpkin Launcher"] = { id = 287, type = "Gun" },
    ["Raw Wolf"] = { id = 288, type = "Consumable" },
    ["Cooked Wolf"] = { id = 289, type = "Consumable" },
    ["Pumpkin Pie"] = { id = 290, type = "Consumable" },
    ["Cursed Pumpkin"] = { id = 291, type = "Ammo" },
    ["Marsh Bar"] = { id = 292, type = "Consumable" },
    ["Peanut Butter Cup"] = { id = 293, type = "Consumable" },
    ["Candy Roll"] = { id = 294, type = "Consumable" },
    ["Scarecrow"] = { id = 295, type = "Bench" },
    ["Salvaged Shotgun"] = { id = 296, type = "Gun" },
    ["Salvaged Shell"] = { id = 297, type = "Ammo" },
    ["Bone Armor"] = { id = 298, type = "Armor", armor_type = "All" },
    ["Armor Plate"] = { id = 299, type = "Attachment" },
    ["Heavy Padding"] = { id = 300, type = "Attachment" },
    ["Night Vision Goggles"] = { id = 301, type = "Attachment", attribute = "NVG" },
    ["Lightweight Padding"] = { id = 302, type = "Attachment", attribute = "SilentSteps" },
    ["Resistant Rubber"] = { id = 303, type = "Attachment" },
    ["Armor Polish"] = { id = 304, type = "Attachment" },
    ["Water Filter"] = { id = 305, type = "Attachment", attribute = "WaterFilter" },
    ["Steel Toes"] = { id = 306, type = "Attachment", attribute = "SteelToes" },
    ["Snorkle"] = { id = 307, type = "Attachment", attribute = "Snorkle" },
    ["Military Backpack"] = { id = 308, type = "Backpack" },
    ["Salvaged Backpack"] = { id = 309, type = "Backpack" },
    ["Salvaged Sniper"] = { id = 310, type = "Gun" },
    ["Military Grenade Launcher"] = { id = 311, type = "Gun" },
    ["Explosive Shell"] = { id = 312, type = "Ammo" },
    ["Salvaged Flycopter"] = { id = 313, type = "Resource" },
    ["Fireplace"] = { id = 314, type = "Bench" },
    ["Black Keycard"] = { id = 315, type = "Tool" },
    ["Salvaged Grenade Launcher"] = { id = 316, type = "Gun" },
    ["Salvaged Explosive Shell"] = { id = 317, type = "Ammo" },
    ["Shotgun Shell"] = { id = 318, type = "Ammo" },
    ["Large Medkit"] = { id = 319, type = "Consumable" },
    ["Small Battery"] = { id = 320, type = "Bench" },
    ["Medium Battery"] = { id = 321, type = "Bench" },
    ["Large Battery"] = { id = 322, type = "Bench" },
    ["Crude Fuel Generator"] = { id = 323, type = "Bench" },
    ["Solar Panel"] = { id = 324, type = "Bench" },
    ["Water Turbine"] = { id = 325, type = "Bench" },
    ["Wire Cutters"] = { id = 326, type = "Tool" },
    ["Button"] = { id = 327, type = "Bench" },
    ["Electric Furnace"] = { id = 328, type = "Bench" },
    ["Electric Heater"] = { id = 329, type = "Bench" },
    ["Switch"] = { id = 330, type = "Bench" },
    ["Windmill"] = { id = 331, type = "Bench" },
    ["Splitter"] = { id = 332, type = "Bench" },
    ["Military Boat"] = { id = 333, type = "Resource" },
    ["Auto Turret"] = { id = 334, type = "Bench" },
    ["Military M39"] = { id = 335, type = "Gun" },
    ["White Ornament"] = { id = 336, type = "Resource" },
    ["Red Ornament"] = { id = 337, type = "Resource" },
    ["Purple Ornament"] = { id = 338, type = "Resource" },
    ["Wreath"] = { id = 339, type = "Bench" },
    ["Christmas Lights"] = { id = 340, type = "Bench" },
    ["Admin Tool"] = { id = 341, type = "Tool" },
}

function M.get_by_name(name)
    return name and M.by_name[name] or nil
end

function M.get(id)
    return id and M.by_id[id] or nil
end

function M.get_by_attribute(attr)
    local name = attr and M.by_attribute[attr]
    if not name then return nil end
    return { name = name }
end

function M.name_for_armor_model(model_name)
    if not model_name or model_name:sub(1, 6) ~= "Armor_" then return nil end
    local id, skin = model_name:match("^Armor_(%d+)/(.+)$")
    if not id then
        id = model_name:match("^Armor_(%d+)$")
        skin = nil
    end
    if id then
        local row = M.by_id[tonumber(id)]
        if row then return row.name, skin end
    end
    local key = model_name:match("^(.-)/") or model_name
    key = key:gsub(" ", "_")
    local num = key:match("^Armor_(%d+)$")
    if num then
        local row = M.by_id[tonumber(num)]
        if row then return row.name, model_name:match("^.-/(.+)$") end
    end
    local attr = key:match("^Armor_(.+)$")
    if attr then
        local row = M.get_by_attribute(attr)
        if row then return row.name, model_name:match("^.-/(.+)$") end
    end
    return nil
end

return M
