from pathlib import Path

src = Path("assets/anime/hiyori/dialogue.txt")
out = Path("assets/anime/april/dialogue.txt")
lines = []
if src.exists():
    for line in src.read_text(encoding="utf-8").splitlines():
        line = line.replace("Hiyori", "April")
        if line.strip():
            lines.append(line)

extra = [
    "combat_enter|roasty|evil|Combat started. Try not to feed them.",
    "combat_enter|roasty|smug|Oh, a fight. This should be educational.",
    "combat_enter|roasty|surprised|Guns out already? Bold for you.",
    "combat_enter|roasty|laugh|You're in combat. Act like it for once.",
    "combat_enter|roasty|pout|Someone wants your inventory. Don't donate.",
    "combat_enter|roasty|evil|Fight mode. Please aim at them, not the floor.",
    "combat_enter|supportive|worried|You're in combat. Keep cover and track angles.",
    "combat_enter|supportive|fear|Fight started. Focus and don't overextend.",
    "combat_enter|supportive|neutral|Combat engaged. Watch flanks and reload timing.",
    "combat_enter|supportive|worried|Stay composed. Win the trade, then heal.",
    "combat_enter|supportive|smile|You've got this. Play smart, not loud.",
    "combat_enter|supportive|neutral|In combat. Prioritize info and positioning.",
    "combat_leave|roasty|smug|Combat over. Somehow you're still breathing.",
    "combat_leave|roasty|pout|Fight ended. Hide your celebration.",
    "combat_leave|roasty|laugh|Out of combat. Don't immediately dive back in.",
    "combat_leave|roasty|neutral|Threat gone. Check ammo before looting.",
    "combat_leave|supportive|happy|Combat cleared. Reset and heal up.",
    "combat_leave|supportive|smile|You're clear. Patch wounds and reload.",
    "combat_leave|supportive|neutral|Out of combat. Take a second to stabilize.",
    "combat_leave|supportive|happy|Nice. Use the downtime wisely.",
    "bleeding|roasty|disgusted|You're bleeding. Congrats on the leak.",
    "bleeding|roasty|pout|Bandage. Now. Your HP is dripping away.",
    "bleeding|roasty|worried|Bleed tick going. Medicine would be smart.",
    "bleeding|roasty|laugh|Red trail unlocked. Stealth is cancelled.",
    "bleeding|roasty|evil|Bleeding already? Peak efficiency.",
    "bleeding|supportive|worried|You're bleeding. Stop and bandage immediately.",
    "bleeding|supportive|fear|Bleed status active. Prioritize a medkit.",
    "bleeding|supportive|sad|Don't ignore the bleed. Fix it before fighting.",
    "bleeding|supportive|worried|Apply a bandage before you lose the fight to ticks.",
    "bleeding|supportive|neutral|Bleeding. Heal, then reassess.",
    "bleed_stopped|roasty|smug|Bleed stopped. Miracles do happen.",
    "bleed_stopped|roasty|smile|Finally patched. Try keeping the blood inside.",
    "bleed_stopped|roasty|neutral|Bleed cleared. Don't reopen it instantly.",
    "bleed_stopped|supportive|happy|Bleed stopped. Nice recovery.",
    "bleed_stopped|supportive|smile|You're sealed up. Stay careful.",
    "bleed_stopped|supportive|neutral|Bleeding resolved. Good timing.",
    "hunger_low|roasty|pout|You're starving. Eat something that isn't a bullet.",
    "hunger_low|roasty|disgusted|Hunger low. Your stomach is louder than your footsteps.",
    "hunger_low|roasty|smug|Hungry already? Professional scavenger energy.",
    "hunger_low|roasty|laugh|Food. Or keep roleplaying a skeleton.",
    "hunger_low|supportive|worried|Hunger is low. Find food before you weaken.",
    "hunger_low|supportive|neutral|Eat soon. Low hunger will punish you later.",
    "hunger_low|supportive|smile|Grab a snack when it's safe.",
    "hunger_low|supportive|worried|Hunger warning. Don't ignore it in a fight.",
    "thirst_low|roasty|pout|Thirsty? Water exists. Shocking, I know.",
    "thirst_low|roasty|disgusted|Your thirst bar is begging for help.",
    "thirst_low|roasty|smug|Dehydration speedrun, classic.",
    "thirst_low|roasty|laugh|Drink something. Sand is not hydration.",
    "thirst_low|supportive|worried|Thirst is low. Get water soon.",
    "thirst_low|supportive|neutral|Hydrate before you commit to another fight.",
    "thirst_low|supportive|smile|Find clean water when you can.",
    "thirst_low|supportive|worried|Low thirst will sneak up on you. Fix it.",
    "radiation|roasty|fear|Radiation. Glow-in-the-dark is not a flex.",
    "radiation|roasty|disgusted|You're cooking in rads. Leave. Immediately.",
    "radiation|roasty|worried|Radiation spike. Suit up or get out.",
    "radiation|roasty|evil|Rads rising. This is how people become lore.",
    "radiation|supportive|fear|Radiation detected. Exit the zone now.",
    "radiation|supportive|worried|You're taking rads. Find cleaner ground.",
    "radiation|supportive|neutral|Radiation active. Prioritize gear or escape.",
    "radiation|supportive|fear|Leave the radiation before it stacks.",
    "cold|roasty|pout|You're freezing. Find heat before you become a popsicle.",
    "cold|roasty|worried|Cold status. Campfire energy, please.",
    "cold|roasty|laugh|Shivering already? Tough guy.",
    "cold|roasty|smug|Temperature dropped. Fashion lost to survival.",
    "cold|supportive|worried|You're getting cold. Warm up soon.",
    "cold|supportive|neutral|Cold warning. Seek heat or warmer gear.",
    "cold|supportive|smile|Find a fire or shelter before it gets worse.",
    "cold|supportive|worried|Stay warm. Cold stacks will hurt.",
    "hot|roasty|disgusted|Overheating. Touch grass... preferably wet grass.",
    "hot|roasty|pout|Too hot. Cool down before you melt your braincell.",
    "hot|roasty|laugh|Heatstroke loading. Smart.",
    "hot|roasty|smug|You're cooking. Not in a cute way.",
    "hot|supportive|worried|You're overheating. Cool off soon.",
    "hot|supportive|neutral|Heat is high. Find shade or water.",
    "hot|supportive|smile|Cool down before committing to a long run.",
    "hot|supportive|worried|Hot status. Manage temperature now.",
    "drowning|roasty|fear|You're drowning. Surface. Now.",
    "drowning|roasty|surprised|Underwater panic hour?",
    "drowning|roasty|laugh|Air is free. Go get some.",
    "drowning|roasty|worried|Drowning. Swim up before this gets stupid.",
    "drowning|supportive|fear|You're drowning! Get to the surface!",
    "drowning|supportive|worried|Air is low. Break the water now.",
    "drowning|supportive|fear|Swim up. Don't fight under there.",
    "drowning|supportive|worried|Drowning status. Prioritize oxygen.",
    "staff_nearby|roasty|surprised|Staff nearby. Behave. Or at least pretend.",
    "staff_nearby|roasty|worried|Mod energy detected. Maybe hide the crimes.",
    "staff_nearby|roasty|smug|Staff in range. Your villain arc is postponed.",
    "staff_nearby|roasty|neutral|Admin proximity. Play nice.",
    "staff_nearby|supportive|worried|Staff nearby. Stay clean and careful.",
    "staff_nearby|supportive|neutral|A staff member is close. Keep it normal.",
    "staff_nearby|supportive|smile|Staff in the area. No funny business.",
    "staff_nearby|supportive|worried|Mod nearby. Focus on surviving, not flexing.",
    "enemy_nearby|roasty|evil|Hostile nearby. Smile for the crosshair.",
    "enemy_nearby|roasty|smug|Someone's close. Don't get caught looking AFK.",
    "enemy_nearby|roasty|surprised|Enemy in range. Ears up.",
    "enemy_nearby|roasty|laugh|Company. Hopefully not smarter than you.",
    "enemy_nearby|roasty|worried|Threat nearby. Check your corners.",
    "enemy_nearby|supportive|worried|Enemy nearby. Slow down and listen.",
    "enemy_nearby|supportive|fear|Hostile close. Ready your aim and cover.",
    "enemy_nearby|supportive|neutral|Someone's in your bubble. Stay alert.",
    "enemy_nearby|supportive|worried|Nearby threat. Don't sprint into them.",
    "enemy_nearby|supportive|smile|Keep composure. You can win this fight.",
    "party_join|roasty|smug|You're in a party. Try not to drag them down.",
    "party_join|roasty|laugh|Teammates acquired. Their mistake.",
    "party_join|roasty|pout|Party up. Share loot like an adult.",
    "party_join|roasty|evil|Squad formed. Chaos with friends.",
    "party_join|supportive|happy|Party joined. Stick together and callouts help.",
    "party_join|supportive|smile|You're teamed up. Watch each other's backs.",
    "party_join|supportive|neutral|In a party now. Share info and stay linked.",
    "party_join|supportive|happy|Nice. Team play wins more than ego.",
    "party_leave|roasty|pout|Party left. Solo queue dignity restored.",
    "party_leave|roasty|smug|Alone again. Just how your decision-making likes it.",
    "party_leave|roasty|neutral|Out of party. Don't get lonely and die.",
    "party_leave|supportive|neutral|You left the party. Stay aware solo.",
    "party_leave|supportive|worried|Solo now. Play safer angles.",
    "party_leave|supportive|smile|Party ended. You've got this alone too.",
    "reviving|roasty|smug|Look at you, being useful for once.",
    "reviving|roasty|smile|Reviving someone. Don't get beamed mid-animation.",
    "reviving|roasty|pout|Hero moment. Cover first, then the revive.",
    "reviving|roasty|laugh|Saving them? Bold charity.",
    "reviving|supportive|smile|Nice revive. Watch your surroundings while you do it.",
    "reviving|supportive|worried|Reviving. Keep an eye on flanks.",
    "reviving|supportive|happy|Good teammate play. Finish the revive safely.",
    "reviving|supportive|neutral|Hold the revive and stay ready to cancel if pushed.",
    "boss_spawn|roasty|evil|Boss event up. Go be brave. Or loot later. I don't care.",
    "boss_spawn|roasty|surprised|Big NPC online. Don't feed it for free.",
    "boss_spawn|roasty|smug|Event boss spotted. Try not to be the highlight reel.",
    "boss_spawn|roasty|laugh|World event. Perfect time for bad decisions.",
    "boss_spawn|roasty|neutral|Boss presence detected. Gear check.",
    "boss_spawn|supportive|surprised|A boss event is active. Prepare before engaging.",
    "boss_spawn|supportive|worried|Boss nearby or up. Watch the area carefully.",
    "boss_spawn|supportive|neutral|World boss event. Coordinate if you can.",
    "boss_spawn|supportive|smile|Event spawn. Opportunity if you're ready.",
    "boss_spawn|supportive|worried|Big threat event. Don't rush blind.",
    "timed_crate|roasty|smug|Timed crate. Race for loot, or race for death. Your call.",
    "timed_crate|roasty|evil|Crate timer up. Campers incoming.",
    "timed_crate|roasty|laugh|Timed crate. Perfect bait for greedy players.",
    "timed_crate|roasty|surprised|Crate event. Don't get third-partied mid-loot.",
    "timed_crate|roasty|pout|Go get shiny boxes. Try surviving the audience.",
    "timed_crate|supportive|happy|Timed crate is up. Approach carefully.",
    "timed_crate|supportive|worried|Crate event active. Check for campers first.",
    "timed_crate|supportive|neutral|Timed crate spotted. Plan your approach.",
    "timed_crate|supportive|smile|Good loot opportunity. Stay aware while opening.",
    "timed_crate|supportive|worried|Crate means contest. Don't tunnel vision.",
    "greeting|roasty|smug|April reporting in. Please be less tragic today.",
    "greeting|roasty|evil|Commentator online. Feed me mistakes.",
    "greeting|supportive|happy|April online. I've got your back.",
    "greeting|supportive|smile|Ready. Call me when it gets spicy.",
    "death|roasty|laugh|Dead again. Collectible achievement unlocked.",
    "death|supportive|sad|Down hard. Reset and come back smarter.",
    "respawn|roasty|smug|Respawned. Let's pretend that was intentional.",
    "respawn|supportive|happy|Fresh life. Start clean.",
    "downed|roasty|laugh|Horizontal again. Iconic.",
    "downed|supportive|worried|Downed. Crawl smart.",
    "safe_enter|roasty|smug|Safe zone. Even chaos needs a break.",
    "safe_leave|supportive|worried|Leaving safety. Eyes open.",
]

seen = set()
final = []
for line in lines + extra:
    if line not in seen:
        seen.add(line)
        final.append(line)

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(final) + "\n", encoding="utf-8")
print(f"wrote {len(final)} lines -> {out}")
